### PR TITLE
Add Upgrade Pokemon Levelling Up

### PR DESCRIPTION
**Pull request by cawk**
Fixed old PR

### CODE REVIEW

**Comment by cawk** [comment]
Code is complete feel free to make changes are any changes you want me to do

**Comment by mich3lam** [comment]
Error CS0136	A local or parameter named 'dgdfs' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

**Comment by mich3lam** [comment]
nvm, issue was on my side. fixed, compiles fine

**Comment by MonsterMMORPG** [comment]
my upgrade logic easier and working. only what it lacks is i can not determine whether pokemon is already max upgraded or not : https://github.com/MonsterMMORPG/Pokemon-GO-Rare-Pokemon-Hunting-Farming-Bot/

**Comment by cawk** [comment]
Renamed variables as were confusing fixed now

**Comment by DeadElle** [comment]
I always done this "by hand" but for lazy people this is awesome :+1:

**Comment by MonsterMMORPG** [comment]
@cawk  i didnt see you also check for whether pokemon is already max level or not?

**Comment by cawk** [comment]
last commit fixes bug with min>max and matches the naming convention in the tasks

**Comment by Newgamer1** [comment]
are you able to use the bot?

**Comment by AriSrijaya** [comment]
please update release 3.3 to 3.4

I have problem with sniping
no pokemon

**Pull request merged**
