### PR TITLE
Update CatchPokemonTask.cs

### PR DESCRIPTION
**Pull request by UntilSunrise**
little fix

Thanks to @maxbrueckl

### CODE REVIEW

**Comment by tensei** [comment]
` var setting = pokemonSettings.FirstOrDefault(q => pokemon != null && q.PokemonId == pokemon.PokemonId);`
` var family = pokemonFamilies.FirstOrDefault(q => setting != null && q.FamilyId == setting.FamilyId);`

worked too

**Comment by yamashi** [comment]
Using @tensei 's suggestion

**Comment by UntilSunrise** [comment]
@yamashi 
With your fix the following code will be never executed if catching a lure/incense pokemon:

                    if (family != null)
                    {
                        family.Candy += caughtPokemonResponse.CaptureAward.Candy.Sum();

                        evt.FamilyCandies = family.Candy;
                    }
                    else
                    {
                        evt.FamilyCandies = caughtPokemonResponse.CaptureAward.Candy.Sum();
                    }

**Comment by tensei** [comment]
yeah well it throws a nullreference so something else needs a fix too

**Pull request closed without merging**
