### PR TITLE
Use InvariantCulture to parse GPX values

### PR DESCRIPTION
**Pull request by Rejaku**
GPX files weren't working with regional settings not using . as decimal seperator.
Thus, I have added CultureInfo.InvariantCulture to all Convert.ToDouble calls related to GPX.

### CODE REVIEW

**Comment by redongreen** [comment]
GPX is not detecting Pokestops along the way to the waypoint.

**Comment by Rejaku** [comment]
Pokestops are detected and used if they are in the radius of the route point. With GPX, the bot follows the path and doesn't orient itself by the stops.
This sounds like a feature request to me, and has nothing to do with the issue here.

**Comment by sloanja** [comment]
@redongreen, the GPX file must have the pathing go directly over the pokestop to register.  The route taken is precise and will not vary to hit the pokestop if you do not program it in precisely.  If you don't know the exact pokestop gps coordinates, you'll need to determine that by looking at Ingress (https://www.ingress.com/intel) or determining exact GPS coordinates when you physically visit the pokestop or other methods not described here.

**Comment by yamashi** [comment]
Master is deprecated.

**Pull request closed without merging**
