### PR TITLE
Better item settings

### PR DESCRIPTION
**Pull request by ReddoKiddo**

### CODE REVIEW

**Comment by LasaFawkes** [comment]
Those values add up to 375 without counting incenses, lucky eggs, lures and incubators. I think the sum should be something along the lines of 330 just to have some spare room for those items, no?

**Comment by ilu01** [comment]
> Those values add up to 375 without counting incenses, lucky eggs, lures and incubators. I think the sum should be something along the lines of 330 just to have some spare room for those items, no?

I am with you in this matter. It has been proposed before, that Pokeballs and Potions may have a maximum sum, and always only the best are stored. e.g. Maximum = 100, if possible 100 ultraballs, if not then 100-x ultraballs, x great balls ... etc.

I am going to try this later if noone beats me to it.

**Comment by ReddoKiddo** [comment]
I have been running this settings last night all night, and it was still able to take more items from pokestop in the morning... So I expect everything to work fine

**Comment by ilu01** [comment]
@ReddoKiddo Well then, try simple math: Pokeballs = 150, Potions = 150, Revives = 75. Those alone are up to 425. How do you think, this may fit in your bags?

**Comment by ThomasSRL** [comment]
This will highly depend on location and speed. I dont think these values are good. Should be under 250/350 depending on level.

**Pull request merged**
