### PR TITLE
Added program pause before continuing with farming.

### PR DESCRIPTION
**Pull request by dually8**
Adds pause feature per this issue: https://github.com/NecronomiconCoding/NecroBot/issues/1091 
#1091

### CODE REVIEW

**Comment by hakkotsu** [comment]
it was already implemented, you can close this PR and wait for release or download source code and compile it by yourself

**Comment by Zerofy** [comment]
The source doesn't pause o.0.

**Comment by hakkotsu** [comment]
img

**Comment by dually8** [comment]
Yeah. That's just on the first run though. This is for every run after that. I'd like to keep this open since at least a few people want this functionality.

**Comment by hakkotsu** [comment]
Maybe it will be better if you incorporate your solution to that one existing already, since your approach indeed gives more flexibility to the user

**Comment by Zerofy** [comment]
i think what he is doing is having it pause at the cord to give you a chance to quit if they are wrong?@dually8 is that right?

**Comment by dually8** [comment]
Isn't that what this pull request is for? I guess I'm not understanding what you're saying exactly.

**Comment by dually8** [comment]
That's right @zerofy

**Comment by hakkotsu** [comment]
That's right but since you should change cords after config was created, this might be not very required feature...

**Comment by hakkotsu** [comment]
@dually8 i mean that there is already code for "pause" after config was created, and it's more logical to use the same function in both places

**Comment by dually8** [comment]
I'll look into what you're talking about when I get a chance tomorrow. I didn't see anything like that while I was browsing the code, but I was just skimming. I still think it's a nice "just in case" action to pause just after showing the coordinates so that you don't accidentally get soft banned.

**Comment by yamashi** [comment]
So is this still applicable ?

**Comment by dually8** [comment]
I'd like to think so, unless you guys have added some sort of "just in case" method when it first boots up.  I haven't gotten a chance to browse through the new commits and whatnot, so I don't know what changes have been made that conflicts with this PR.  If you decide to close this PR, I hope that you will add some sort of feature that pauses and shows the user the coordinates before continuing.  I think this would prevent a lot of accidental soft-bans.

**Comment by yamashi** [comment]
Yes we did add a pause.
Actually the program will exit if no config files exist and tell you to go change them.

**Comment by dually8** [comment]
That's not really the same thing I've done, but alright.  If anything, I think the default lat and long should pull from the first lat and long of the GPX track if that flag is enabled. I think this will keep users from starting in central park and teleporting to somewhere like Santa Monica.

**Comment by dually8** [comment]
Anyone want to explain why the issues section has been closed?  Is this moving to closed source? Or were there just so many you guys were overwhelmed?

**Comment by hakkotsu** [comment]
Probably because of overwhelming script kiddie requests about config problems. Totally not related to development or actual issues. And now they moved to spam in PR's...

**Comment by dually8** [comment]
I'm sorry to hear that.  I was happy to see a proper pause mechanism in the latest release though.  Good work. :)

**Pull request closed without merging**
