### PR TITLE
Revert "Better pokeball choosing"

### PR DESCRIPTION
**Pull request by Owinger**
Reverts NecronomiconCoding/NecroBot#456

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
is there any reason to do that?

**Comment by Owinger** [comment]
@NecronomiconCoding The previous values were perfect.

**Comment by solenrus** [comment]
no, they were way too high, I'm lvl 32 almost and I never seen it use an ultraball with old values

**Comment by Sylencer90** [comment]
The bot very rarely used super/ultra ball, im okay with the current way it is. Im free that it uses more.

**Comment by solenrus** [comment]
don't revert, thanks

**Comment by Owinger** [comment]
@solenrus You obviously don't understand how the code works.

**Comment by Owinger** [comment]
@Sylencer90 What level are you?

What is a Super Ball?

**Comment by mich3lam** [comment]
@solenrus then change it locally. this change is good. thank you. bye.

**Comment by Owinger** [comment]
I see the bot using Ultra Balls constantly. I am level 30.

I am using the old version.

**Comment by roteak** [comment]
You removed use on IV% and prob.
No thanks. 

DO NOT REVERT. 

IV > CP

**Comment by yamashi** [comment]
Master is deprecated.

**Pull request closed without merging**
