### PR TITLE
Polish Translation

### PR DESCRIPTION
**Pull request by GTXMike**
Will try to keep this file up to date with new versions.

### CODE REVIEW

**Comment by shejk0** [comment]
What for? I don't think it's too hard to understand these few words...

**Comment by GTXMike** [comment]
well i noticed that they added translation file in release 0.1.7 so i thought why not if there is a possibility?

**Comment by cebuladeals** [comment]
Zaktualizujesz tlumaczenie?

**Comment by GTXMike** [comment]
Yes i will do it when fin work.

**Comment by GTXMike** [comment]
Any suggestions?

**Comment by cebuladeals** [comment]
Dlaczego nie piszesz po polsku? W nowej wersji brakuje pare elementow.

**Comment by GTXMike** [comment]
Pobralem wersje 0.2.1 w pliku jezykjowym EN nie ma nic, jak ja mam to teraz przetlumaczyc?

**Pull request merged**
