### PR TITLE
KeepMinDuplicatePokemon can now be set to zero

### PR DESCRIPTION
**Pull request by Nordiii**
Made it possible to transfer Pokemon when you have only one of this type left.
Fixes an error when you wanted to transfer your best Pokemon(last one).

(In case you only want Pokemons reaching your criterion)

### CODE REVIEW

**Comment by solenrus** [comment]
its neat, but at the same time u wont be able to see how many candies u have for specific pokemon untill you get one meeting your criterion, still might be useful to some

**Comment by Nordiii** [comment]
You'r right didn't think about this one!
Could dump this info into a File....
Since probably no one would use this when he wants to run around later

Thanks!

**Comment by wetshrimp** [comment]
nordii i was looking for a solution to this, thanks!

now the only question is how we can deal with candies. my proposal is that we can code something that keeps 1 of certain types that are constantly evolved (pidgey, ratata, caterpie, etc)

**Comment by Nordiii** [comment]
You could add them to "ConfigPokemonsToKeep", when you use auto evolve it will discard them anyways after evolving!

**Comment by wetshrimp** [comment]
good point! im sure that will work but some evolutions will break the CP barrier (over 1k for me) like raticate and zubats and then ill be quite upset with 200 of them!!! :)

**Comment by yamashi** [comment]
Master is deprecated.

**Pull request closed without merging**
