### PR TITLE
[Feature] catch and find lure incense pokemon

### PR DESCRIPTION
**Pull request by UntilSunrise**
Catching incense pokemon should work if
https://github.com/AeonLucid/POGOProtos/pull/81
is accepeted and included in the proto nuget packet.

Currently the incense encounter id is alway 0 so we dont get a valid encounter

### CODE REVIEW

**Comment by Ilses** [comment]
Nice work!

**Comment by Ilses** [comment]
I clearly haven't used C# in years.. I forgot dynamic was a thing. That said, I can't help but feel the code would have been cleaner if you'd overloaded Encounter's Execute function.

**Comment by maxbrueckl** [comment]
I guess there is a problem with this merge. A null pointer exception, that is happening when encounter lured pokemon.

In: CatchPokemonTask.cs:88 - pokemon is null
In: CatchLurePokemonsTask.cs:41 - Execute(_,_,_,null,_,_); is called.

I did apply a workaround:

```               
               var pokemon = new POGOProtos.Map.Pokemon.MapPokemon
                {
                    EncounterId = encounterId,
                    ExpirationTimestampMs = currentFortData.LureInfo.LureExpiresTimestampMs,
                    Latitude = currentFortData.Latitude,
                    Longitude = currentFortData.Longitude,
                    PokemonId = pokemonId,
                    SpawnPointId = currentFortData.LureInfo.FortId
                };
```
...
`CatchPokemonTask.Execute(ctx, machine, encounter, pokemon, currentFortData, encounterId);`

**Comment by solenrus** [comment]
can anyone push a fix for it? @maxbrueckl

**Comment by UntilSunrise** [comment]
is fixed

**Pull request merged**
