### PR TITLE
[FEATURE] Save profile - pokemon list in csv file

### PR DESCRIPTION
**Pull request by marksterxxx**
This is for the nerds who want to optimize their pokemon
-generate profile_{username} folder
-pokemon list is saved in pokemon.csv
-list contains pokemon stats and url link for analysis

### CODE REVIEW

**Comment by ilu01** [comment]
I love minmaxing and this feature

**Comment by solenrus** [comment]
perfect, had to do all this manually by editing the number of perfect % list number

**Comment by ilu01** [comment]
Just a question: Why does the % of perfection is not calculated by adding the IVs and dividing by 45? 
(IV_STAM+IV_DEF+IV_ATT)/45 as everyone else does.

**Comment by marksterxxx** [comment]
@ilu01 I don't know 

credits to this site: https://jackhumbert.github.io/poke-rater/ for the cool analysis
been looking at his script: https://jackhumbert.github.io/poke-rater/js/index.js
I think his battle rating formula is a good thing to use for sorting pokemon
capture

**Comment by solenrus** [comment]
yea, it looks great!

**Comment by 5andr0** [comment]
@ilu01 because it's incorrect. IV_ATT has more weight. And it's different for every pokemon based on their base stats

**Comment by solenrus** [comment]
tested, it works, but it saves and updates way too often, currently after each pokestop
make this on a timer, like on startup and then every "X" min onward.
Needs and option added to the settings to customize the timer.

Cheers

**Comment by solenrus** [comment]
also the formatting in the .csv is kinda fucked for me, not sure if that's my excel but it's kinda unusable as is, cant really access the links right of the bat

**Comment by solenrus** [comment]
some of the links were defaulted to bulbasaur on the website, maybe something wrong with the formatting?

**Comment by Shroomzie** [comment]
@solenrus click it a few times...

**Comment by solenrus** [comment]
@Shroomzie no, it just gets redirected here https://jackhumbert.github.io/poke-rater/#MSw1LDUsMTM4LDI4
for example this link 

> Dragonite,,3048,80,1701730682221,SteelWingFast,HyperBeam,147,15,4,15,https://jackhumbert.github.io/poke-rater/#MTQ5LDMxLDMyLDUsMzA0OCwxNDc=

**Comment by Shroomzie** [comment]
like i said, Repeat the process of going to your desired poke a few times.

**Comment by dbfy** [comment]
wow this is super neat, is there a source code for the rater?

**Comment by marksterxxx** [comment]
@dbfy I can't find his source code... But it is mostly in html and javascript, look at this file for his formulas
https://jackhumbert.github.io/poke-rater/js/index.js

**Comment by nwg5817** [comment]
Love this. Really helpful so far!

**Comment by ellm62** [comment]
+1

**Comment by yamashi** [comment]
Master is deprecated.

**Comment by 5andr0** [comment]
Can you make a separated request for SaveProfilePokemons only for the new master branch? A boolean setting for this feature would be nice. Please don't commit your .sln this time.

**Comment by salvob41** [comment]
Link to https://jackhumbert.github.io/poke-rater/ doesn't work anymore

**Comment by nwg5817** [comment]
Markster can you update this for the latest source?

**Comment by ilu01** [comment]
Is this feature planned to be implemented anytime near? Would be very helpful!

**Pull request closed without merging**
