### PR TITLE
adding initial code for incense and incubators, untested

### PR DESCRIPTION
**Pull request by Valmere**
won't mess anything up, just pushing some code before I go to sleep incase anyone else wants to play with it

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
Thanks. Leaving open until someone tested it

**Comment by Maglin** [comment]
I went to test.  Couldn't find where to turn on incense or incubators.

**Comment by Valmere** [comment]
Wasn't anywhere to turn it on lol, no functions were added to the logic. I'm up now, going to grab some food before finishing implementing

**Comment by patrikwlund** [comment]
I added incubation to my private version, which is based on Ferox's, with updated protos from https://github.com/AeonLucid/POGOProtos, so there may be some differences in naming. Feel free to use it.

Here's the logic I use for incubation:
```
private async Task UseAllIncubators()
{
    var playerStats = (await _inventory.GetPlayerStats()).FirstOrDefault();
    if (playerStats == null)
        return;

    var kmWalked = playerStats.KmWalked;

    var incubators = (await _inventory.GetIncubators())
        .Where(x => x.UsesRemaining > 0 || x.ItemId == ItemId.ItemIncubatorBasicUnlimited)
        .OrderByDescending(x => x.ItemId == ItemId.ItemIncubatorBasicUnlimited)
        .ToList();

    var unusedEggs = (await _inventory.GetEggs())
        .Where(x => string.IsNullOrEmpty(x.EggIncubatorId))
        .OrderBy(x => x.EggKmWalkedTarget - x.EggKmWalkedStart)
        .ToList();

    foreach (var incubator in incubators)
    {
        if (incubator.PokemonId == 0)
        {
            var egg = incubator.ItemId == ItemId.ItemIncubatorBasicUnlimited
                ? unusedEggs.FirstOrDefault()
                : unusedEggs.LastOrDefault();

            if (egg == null)
                return;

            var response = await _client.UseEggIncubator(incubator.Id, egg.Id);
            Logger.Write($"Putting egg in incubator ({response.EggIncubator.TargetKmWalked - kmWalked:0.00}km left)");

            unusedEggs.Remove(egg);
            await Task.Delay(500);
        }
        else
        {
            Logger.Write($"Incubator status update: {incubator.TargetKmWalked - kmWalked:0.00}km left");
        }
    }
}
```

It prefers unlimited incubators for short eggs, and consumable incubators for the long ones.

I run it between pokestops if the user has traveled more than 1km, and after every completed run.

**Comment by kducvn** [comment]
how's about lucky egg?

**Comment by Valmere** [comment]
popping lucky eggs during evolution was implemented hours ago. incense is coming along, able to use it, finishing up the requests and responses for getting the spawned pokemon

**Comment by kducvn** [comment]
Would you like to add feature to use lucky eggs every a flexible time or when i have lucky eggs.

**Comment by joshk6656** [comment]
@patrikwlund could you provide the other functions used in your code?

GetIncubators / UseEggIncubator

**Comment by patrikwlund** [comment]
@joshk6656 

```
// Inventory.cs

public async Task<IEnumerable<PokemonData>> GetEggs()
{
    var inventory = await _client.GetInventory();
    return
        inventory.InventoryDelta.InventoryItems.Select(i => i.InventoryItemData?.PokemonData)
            .Where(p => p != null && p.IsEgg);
}

public async Task<IEnumerable<EggIncubator>> GetIncubators()
{
    var inventory = await _client.GetInventory();
    return inventory.InventoryDelta.InventoryItems
        .Where(x => x.InventoryItemData.EggIncubators != null)
        .SelectMany(i => i.InventoryItemData?.EggIncubators?.EggIncubator)
            .Where(i => i != null);
}

// Client.cs

public async Task<UseItemEggIncubatorResponse> UseEggIncubator(string incubatorId, ulong pokemonId)
{
    var customRequest = new UseItemEggIncubatorMessage
    {
        ItemId = incubatorId,
        PokemonId = pokemonId
    };

    var releasePokemonRequest = RequestBuilder.GetRequest(await GetValidAuthTicket(), CurrentLat, CurrentLng, CurrentAltitude,
        new Request
        {
            RequestType = RequestType.UseItemEggIncubator,
            RequestMessage = customRequest.ToByteString()
        });
    return await _httpClient.PostProtoPayload<RequestEnvelope, UseItemEggIncubatorResponse>($"https://{_apiUrl}/rpc", releasePokemonRequest);
}
```

Note: Both eggs (pokemon) and incubators are in the inventory, so they could be fetched in just one request. I just didn't build it that way for whatever reason.

**Comment by knguye12** [comment]
@patrikwlund have you coded using lucky egg every 30mins? or every 1hour?
if yes, please share!

**Comment by patrikwlund** [comment]
@knguye12: I haven't done anything with lucky eggs, sorry.

**Comment by MonsterMMORPG** [comment]
i have tried your built but it messed mine so badly :( i guess i will add manually

**Comment by MonsterMMORPG** [comment]
does UseIncubatorRequest works? i cant see anywhere you have called : UseAllIncubators

**Comment by MonsterMMORPG** [comment]
@patrikwlund  can you please share these 2 functions?

_inventory.GetIncubators()
_inventory.GetEggs()
_client.UseEggIncubator

And whatever they require to work :D

**Comment by MonsterMMORPG** [comment]
@patrikwlund  i am getting these errors after i have added your code to my build : https://github.com/MonsterMMORPG/Pokemon-Go-Bot

errors

**Comment by patrikwlund** [comment]
@MonsterMMORPG: I've already shared those 3 methods. Just put them in their respective classes, rename anything that doesn't have the same name in this repo (remember, I didn't build these in NecroBot and used different protos) and then call `await UseAllIncubators()` wherever you want in Logic.cs

The changes to Client.cs require updated protos (or rather, the generated C# code) that include the UseIncubator-stuff. I got mine from https://github.com/AeonLucid/POGOProtos, but I can see that @Valmere added the necessary request class to Payloads.cs as part of a commit in this PR. That should be enough.

**Comment by MonsterMMORPG** [comment]
@patrikwlund  ty but i cant make it work :( any chance you can share your project so i can copy from there? or can you look at my fork? https://github.com/MonsterMMORPG/Pokemon-Go-Bot

**Comment by patrikwlund** [comment]
@MonsterMMORPG: I have no intention of putting it on github, but I zipped it in its current state for you here (temporary link): https://drive.google.com/file/d/0B8NkUHiKA6N0LXZRcE03SHNqOEk/view?usp=sharing

Please let this thread be about the PR now :)

**Comment by MonsterMMORPG** [comment]
@patrikwlund ty very much. i see your API is completely different than ours :(

**Comment by skupfer** [comment]
cannot wait for it, was about to do the same this morning but saw your PR... phew, dodged a bullet xD

**Comment by yamashi** [comment]
Master is deprecated.

**Pull request closed without merging**
