### PR TITLE
Rename all pokemon with IV that aren't already nicknamed.

### PR DESCRIPTION
**Pull request by Sekioh**
Adds another configuration option that renames anything that's not custom named, to be another choice over the renaming only above capture IV minimums.

### CODE REVIEW

**Comment by hilycker** [comment]
Was looking for this, nice one

**Comment by tr0n0s** [comment]
add this please :D

**Comment by Spaeck** [comment]
great feature, id love to see it merged!

**Comment by ShawnHardwick** [comment]
Conflicted pull request. Closing as we prepare for a new release. Resubmit if the new release still needs this implemented.

**Comment by NecronomiconCoding** [comment]
fix conflicts

**Pull request closed without merging**
