### PR TITLE
Error after "program will continue after keypress"

### PR DESCRIPTION
**Pull request by Cx974**
Logs me in, I press a key to continue and:

[14:14:52] Program will continue after the key press...
[14:14:52] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__19.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Inventory.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__12.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Inventory.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\InfoState.cs:line 15
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 34

### CODE REVIEW

**Comment by XtracT** [comment]
Program will continue after key press should be time based. People leave Necrobot overnight, and if servers go down and error occurs, having to press a key keeps the bot from doing its task.

**Comment by Cx974** [comment]
But how do I fix the actual error I'm getting in red text?

**Comment by vpvp** [comment]
I have same problem...

**Comment by N4MeD** [comment]
Same

**Comment by igryk** [comment]
Same here

**Comment by Connor2key** [comment]
I'd also appreciate a quick tutorial on how to resolve this issue. Love the work you guys do but have no idea about any of this technical stuff. Thanks.

**Comment by Yeladim** [comment]
Same error, anyone has resolved this?

**Comment by Cx974** [comment]
Apparently not

**Pull request closed without merging**
