### PR TITLE
Added some nests

### PR DESCRIPTION
**Pull request by mich3lam**

### CODE REVIEW

**Comment by OverlordQ** [comment]
This is a broken commit. For the love of god, somebody remove your commit access.

**Comment by mich3lam** [comment]
@OverlordQ not really.. it isnt lol

**Comment by mich3lam** [comment]
Wait wtf you are right.
fixed it https://github.com/NecronomiconCoding/NecroBot/pull/1310

**Comment by GitMeNot** [comment]
More nests:

https://www.reddit.com/r/TheSilphRoad/comments/4t3o06/examining_nests/
https://www.google.com/maps/d/viewer?mid=1anyDs-H7hOtGQaxaTwuLjulUrVM

(But not in right format)

**Pull request merged**
