### PR TITLE
Refactor Execute() in CatchPokemonTasks.cs to fix 3 bugs with catching incense Pokemon.

### PR DESCRIPTION
**Pull request by Ilses**
This PR supersedes PR #778 where the bugs are described. I have confirmed this refactor works when catching regular, incense, and lured Pokemon.

### CODE REVIEW

**Comment by Ecalite** [comment]
What happened to lured pokemons working as intended? :)

**Comment by Ilses** [comment]
Oops, I meant incense. Although they're technically lured, that was unclear -- sorry about that!

**Comment by UntilSunrise** [comment]
argh, thought about it while writing the incense code xD Thank you for finding this issue ;)

Sadly, we still have to wait for https://github.com/AeonLucid/POGOProtos/pull/81 . If this didn't get merged encounter_id for incense pkm will always be 0 ...

**Comment by Ilses** [comment]
Note: Used in PR #946, which resolves conflicts.

**Comment by NecronomiconCoding** [comment]
thanks fix conflicts and reopen

**Pull request closed without merging**
