### PR TITLE
fix crash for me 

### PR DESCRIPTION
**Pull request by lnkakalink**
1 start bot 
2 go http://crapware.aidf.org/page/clickermann
3 download http://crapware.aidf.org/files/7/
4 record scenario
my scenario 

  keyDown(81)
  keyDown(81)

5 time-out re-start 1650 sec
6 start clickermann 
7 click on the bot window

### CODE REVIEW

**Comment by Silverarrows1986** [comment]
`@echo off
:loop
start NecroBot.exe
timeout /t 1800 >null
taskkill /f /im NecroBot.exe >null
timeout /t 5 >null
goto loop`

Als .bat Datei speichern. So kann man es ohne fremd Software machen.

**Comment by lnkakalink** [comment]
if you will upgrade it to update settings and stray after prolonged use, I can not see

**Comment by lnkakalink** [comment]
@Silverarrows1986 and start bot write me pls key for start

**Comment by Silverarrows1986** [comment]
[run.zip](https://github.com/NecronomiconCoding/NecroBot/files/391614/run.zip)

Just double click it, after copy it to main folder from Necrobot

**Comment by lnkakalink** [comment]
hyxil2emb0mzxe9vbonz9w 1
@Silverarrows1986 how to fix it does not stop at this point

**Comment by stellaris1** [comment]
@lnkakalink disablestartdelay change from true to false

**Comment by massi93** [comment]
he

Does anybody been thorugh this? It keeps saying that over and over like  loop

**Comment by faris2000** [comment]
i have same looping problem
 (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by LeagueRaINi** [comment]
just use "StartupWelcomeDelay": false, dafuq o.o

**Comment by massi93** [comment]
your fix is not working

**Comment by hasan1891** [comment]
capture
how to fix it? it appear while i start bot

**Pull request closed without merging**
