### PR TITLE
Offset parameter

### PR DESCRIPTION
**Pull request by Ryuichiro**
Fixed version for randomized spawn location.
[#1430](https://github.com/NecronomiconCoding/NecroBot/pull/1430)

### CODE REVIEW

**Comment by Ryuichiro** [comment]
Now based on position and in meters.

**Comment by Zuxser** [comment]
Did you tested it?
_settings.MaxSpawnLocationOffset is type of int? So you dividing int with an much more larger int - does it cause fraction loss and 0 as a result? 
return _settings.DefaultLatitude + _rand.NextDouble() * (_settings.MaxSpawnLocationOffset / 111111);
return some value + (random value * 0) -> return some value

**Comment by Ryuichiro** [comment]
@Zuxser Not sure, it worked so I didn't take a closer look. But I will make a fixed Pull request to be sure.

**Comment by Ryuichiro** [comment]
[#1461](https://github.com/NecronomiconCoding/NecroBot/pull/1461)

**Pull request merged**
