### PR TITLE
bug sniper add snorlax config.json 

### PR DESCRIPTION
**Pull request by xMasterSolidx**
configuration
"PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      },
      {
        "Latitude": 37.780368959,
        "Longitude": -122.388275515
      }
    ],
    "Pokemon": [
      "Dratini",
      "Magikarp",
      "Eevee",
      "Charmander",
      "snorlax"
    ]
  }

[23:18:45] [Sniper] Scanning for Snipeable Pokemon at 38.5568074864611,-121.238379478455...
[23:18:45] System.ArgumentException: No se puede encontrar el valor solicitado 'snorlax'.
   en System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   en System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   en System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   en PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<>c.<Execute>b__1_0(String q) en D:\Dev\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:línea 69
   en System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   en System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   en System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   en System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   en PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<>c__DisplayClass1_0.<Execute>b__2(PokemonLocation q) en D:\Dev\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:línea 73
   en System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__1.MoveNext() en D:\Dev\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:línea 72
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() en D:\Dev\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:línea 155
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() en D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:línea 42
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() en D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:línea 35
[23:18:45] Logging in using Google

### CODE REVIEW

**Comment by Zerofy** [comment]
"snorlax" to "Snorlax"

**Comment by simplyblue333** [comment]
Fixed, check https://github.com/NecronomiconCoding/NecroBot/pull/1333 for full config
[config2.txt](https://github.com/NecronomiconCoding/NecroBot/files/389884/config2.txt)

**Comment by kaeus** [comment]
This is not a valid PR. Please dont create PR to show bugs unless you are fixing something.

**Comment by jkoeb8762** [comment]
@kaeus  Question: then where do we bring up issues?? Cannot see a issue branch...

**Comment by panthernet** [comment]
Issues are closed due to overkill number of people trying to report. Use chats, usually devs see what's wrong and fix it. Or fix it by yourself and make pull.

**Pull request closed without merging**
