### PR TITLE
Fixed MinPokeballsToSnipe

### PR DESCRIPTION
**Pull request by Ryuichiro**
Now the Bot will snipe until he's out of pokeballs and tell you why he
stopped or didn't start.

I never worked with CancellationToken so please double check the code.

### CODE REVIEW

**Comment by Diablosito33** [comment]
It's just me, or bot only snipes with PokeBalls?
I normally recycle all pokeballs, and snipe doesn't go with Greatballs or so...

**Comment by Ryuichiro** [comment]
No he doesn't BUT he stops sniping if you fall below the CancellationToken value.
For example with CancellationToken = 100 he will stop sniping if you fall to 99 Pokeballs and most likely he hasn't touched the higher tier pokeballs except for really hard catches. ^^

**Comment by Ryuichiro** [comment]
Added MinPokeballsWhileSnipe which takes place of the old MinPokeballsToSnipe.
The Bot will end sniping if you have only MinPokeballsWhileSnipe pokeballs left.
It will not check the type of the pokeballs, but the bot uses them optimal, so I see no problem there.

**Comment by mythosknight** [comment]
My snipe has not been working as of late. I have it set to snipe 5 different locations with only a few Pokemon. Is this the case for everyone else or is it something on my end?

  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      },
      {
        "Latitude": 27.994401411046173,
        "Longitude": 101.953125
      },
      {
        "Latitude": -27.371767300523032,
        "Longitude": 135.3515625
      }
    ],
    "Pokemon": [
      "Dratini",
      "Bulbasaur",
      "Ivysaur",
      "Venusaur",
      "Bellsprout",
      "Weepinbell",
      "Victreebel",
      "Kangaskhan"
    ]
  }

**Comment by ShallowHacker** [comment]
@mythosknight Snipe is broken atm. When the update is released it will fix out programs and make them even better. Until then, compile yourself or wait. That's all you can do.

**Comment by mythosknight** [comment]
@ShallowHacker thank you for the information and the reply. I will patiently wait until then. Thanks.

**Comment by Ryuichiro** [comment]
Merged the newest master, still no conflicts.

**Comment by vcafezinho** [comment]
@ShallowHacker @Ryuichiro Guys I have the last version with those confs. still not showing any infos about Snipe, do I have something wrong? 

  "MinPokeballsToSnipe": 0,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,
  "UseTransferIVForSnipe": false,
  "SnipeIgnoreUnknownIV": false,
  "MinDelayBetweenSnipes": 500,

"PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": -33.822988,
        "Longitude": 151.188749
      },
      {
        "Latitude": 49.2873196,
        "Longitude": -122.8414993
      },
      {
        "Latitude": 49.278544,
        "Longitude": -123.103376
      },
      {
        "Latitude": 33.292869,
        "Longitude": -111.741306
      }
    ],
    "Pokemon": [
      "alakazam",
      "blastoise",
      "venusaur",
      "charizard",
      "dragonite",
      "gyarados",
      "eevee",
      "snorlax"
    ]

**Comment by Ryuichiro** [comment]
My Pull Request isn't a tech support :disappointed: 
Please ask your questions on discord.
Try disabling "UseSnipeLocationServer"

**Comment by vcafezinho** [comment]
@Ryuichiro Sorry =/

**Comment by Ilses** [comment]
I still seem to be getting the bot to scan with mins set to 1 & 1. Possibly inventory cache issues.

**Comment by tn1314** [comment]
I got the same problem with PokemonToSnipe. All the locations just Stop working a few hours ago. Now it just said "No pokemon to snipe" even it has (I checked the actual locations by pokevision)

**Comment by Ryuichiro** [comment]
I will close this Pull request and submit a new one based on the actual master and with a clear description.

**Pull request closed without merging**
