### PR TITLE
Still getting the same error, help?

### PR DESCRIPTION
**Pull request by exoticminge**
Unhandled Exception: Newtonsoft.Json.JsonReaderException: After parsing a value
an unexpected character was encountered: ". Path 'PokemonsNotToTransfer[14]', li
ne 156, position 4.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(Jso
nReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IL
ist list, JsonReader reader, JsonArrayContract contract, JsonProperty containerP
roperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(Json
Reader reader, Type objectType, JsonContract contract, JsonProperty member, Obje
ct existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValu
e(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract
containerContract, JsonProperty containerProperty, JsonReader reader, Object tar
get)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(
Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty m
ember, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Js
onReader reader, Type objectType, JsonContract contract, JsonProperty member, Js
onContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
 objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, Jso
nSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSeriali
zerSettings settings)
   at PoGo.NecroBot.CLI.GlobalSettings.Load(String path) in C:\Users\TYLaptop\De
sktop\BOT\NecroBot-master\PoGo.NecroBot.Logic\Settings.cs:line 264
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\TYLaptop\Desktop
\BOT\NecroBot-master\PoGo.NecroBot.CLI\Program.cs:line 31
Press any key to continue . . .

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
just use "" and dont forget commas

**Comment by exoticminge** [comment]
still have no clue where to put them :/

**Comment by BuckFrandon** [comment]
should be 
"PtcUsername" : "username",
"PtcPassword" : "password".

**Comment by mochdev** [comment]
chek this 
   "PokemonsNotToTransfer": [
    "aerodactyl",
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"

**Comment by exoticminge** [comment]
And which file am I changing it in?

**Comment by mochdev** [comment]
config.json

**Comment by exoticminge** [comment]
Both are fine, and yet still getting the same error :/

**Comment by mochdev** [comment]
try to download realease.zip then extract it, and set it again.
or maybe u can do clean config

**Comment by ogsstyle** [comment]
i have the same issue with the latest release v0.2.1, but work well with v0.2.0, connect ptc and my modified config.

**Comment by grompes** [comment]
Реально косяк. Действитльно не работает. Удаление config не помогает. Авторизация через google.

chek this
 "PokemonsNotToTransfer": [
 "aerodactyl",
 "venusaur",
 "charizard",....
так же не помогает

Плюч ко всему в Папке Release лежит другая папка release... Косяк на косяке

**Pull request closed without merging**
