### PR TITLE
Added Prioritize IV over CP toggleable option

### PR DESCRIPTION
**Pull request by PocketMobsters**
Per issue #241

### CODE REVIEW

**Comment by solenrus** [comment]
Omfg, yes! I love you!

**Comment by PocketMobsters** [comment]
I've got you fam, no worries.

**Comment by decryptionz** [comment]
IV YAS

**Comment by solenrus** [comment]
did you forget to add the toggle to the UserSettings.settings builder or? cause I don't see the actual toggle, unless it's not supposed to be there

**Comment by PocketMobsters** [comment]
I did indeed add that, you can find that in this part of the pull request https://github.com/NecronomiconCoding/NecroBot/pull/265/commits/8d2b3daa40035bd9893097aa797203bc6d0fc9ec

**Comment by Shroomzie** [comment]
Error	CS1061	'UserSettings' does not contain a definition for 'PrioritizeIVOverCP' and no extension method 'PrioritizeIVOverCP' accepting a first argument of type 'UserSettings' could be found (are you missing a using directive or an assembly reference?)

**Comment by CTDragon** [comment]
Designer code was submitted, but not the UserSettings.settings file

**Comment by PocketMobsters** [comment]
Yes you are right, give me a minute.

**Comment by solenrus** [comment]
add that pull to this current commit then, cause it's split, I straight up downloaded your whole git to testrun it and it was missing there, not here.

**Comment by PocketMobsters** [comment]
Added, hopefully it updates here. I'm new to Github so I apologize for any weird happenings.

**Comment by CTDragon** [comment]
Also, this may be an opinion thing, but I'll mention it again anyway, do we really want to include IndividualAttack in the IV calculation for pokemon that can evolve since abilities randomize when evolved? Is that based of the abilities? That could always be changed later of course.

        public double CalculateIV()
        {
            return ((double)(IndividualAttack + IndividualDefense + IndividualStamina) / (3.0f * 15.0f)) * 100.0f;
        }

**Comment by Shroomzie** [comment]
its good practice to have a testing branch. It is bad practice to merge code into master that breaks it.

**Comment by solenrus** [comment]
compiles works now, lets see if it actually keeps IV>CP

**Comment by solenrus** [comment]
https://gyazo.com/340b414a98787fa7e04568dbfcfdfe9c
my setings are 95% IV and 2000 CP and TrasnferDuplicatePokemon is obviously on true, but wasn't it supposed to leave that Oddish, because now we have 0 of those left.

**Comment by PocketMobsters** [comment]
I did not change any functionality except sorting by IV instead of CP. They work functionally the same except OrderByDescending(x => x.Cp) is p.OrderByDescending(x => x.CalculateIV())

**Comment by solenrus** [comment]
ok, well, I definitely want this change added to the master regardless!

**Pull request merged**
