### PR TITLE
Refactor CatchPokemonTasks.cs execute function & fix incense

### PR DESCRIPTION
**Pull request by Ilses**
Fixes 3 bugs with catching incense Pokemon described in PR #778.

### CODE REVIEW

**Comment by Ilses** [comment]
Incense seems to be working locally, but can I get someone independent to confirm?

**Comment by yamashi** [comment]
Waiting for someone to test this.

**Comment by Pakobbix** [comment]
Testing it right now with the 774commits version (used it in com.6xx, too, works fine without errors/issues

**Comment by csutcliff** [comment]
Works great here

**Comment by Ilses** [comment]
Welp, new master has updated enough that we conflict again. I'll address them in a few hours when I'm less tired.

**Comment by Ilses** [comment]
Updating this now -- looks like most changes are ctx -> session

**Comment by Ilses** [comment]
Putting this in a new PR. Lures are broken upstream, so a rebase seemed more appropriate than a fixup commit until we can verify that functionality will still work.

**Pull request closed without merging**
