### PR TITLE
Enough Said

### PR DESCRIPTION
**Pull request by OverlordQ**
It's clear he doesnt know anything about repo or distributed development.

### CODE REVIEW

**Comment by OverlordQ** [comment]
It's clear he's salty he got called out for commit broken untested code.

**Comment by trana315** [comment]
Who you talking about? Necro?

**Comment by mich3lam** [comment]
@trana315 nah... @OverlordQ is salty af.. I pushed the wrong commit, someone merged it and it was wrong. it was fixed and waiting for new merge but he is salty cause he can't do things his own and gets mad when people fuck up :)

**Comment by yamashi** [comment]
Write me an essay please then send it to employer and tell them how bad I am.

**Comment by mich3lam** [comment]
@yamashi xd that made me actually giggle

**Pull request closed without merging**
