### PR TITLE
Adjustments for MultiProfiles

### PR DESCRIPTION
**Pull request by 5andr0**
Fixed an issue where config/auth.json wasn't loading from the profile subdir.
Logs are written into profile subdirs to avoid writing conflicts. It was working before, but somebody broke it (https://github.com/NecronomiconCoding/NecroBot/commit/e62da1d63025700f10b214f72d412e3cc7c675ad)
User login prompt will now only pop up when there is no auth.json at the default or profile path. Entered logins will be stored in the newly created auth.json

### CODE REVIEW

**Comment by hakkotsu** [comment]
Issue was introduced after this [commit](https://github.com/NecronomiconCoding/NecroBot/commit/e62da1d63025700f10b214f72d412e3cc7c675ad) causing all logs being stored in one file and bot throwing `System.IO.IOException: The process cannot access the file`

**Comment by Ilses** [comment]
Thanks! I almost missed seeing this PR

**Comment by hakkotsu** [comment]
I've closed my own PR because i missed this one. First [commit](https://github.com/NecronomiconCoding/NecroBot/pull/749/commits/8ac49ca8b39cc0a3513f3433021247f071bdbe49) should work, not sure about second

**Comment by Ilses** [comment]
also add at Program.cs:44
subPath = subPath.Replace("/", "\\");
and everything should be good for the PR

**Comment by 5andr0** [comment]
Hmm why the / \ replace? Path.DirectorySeparatorChar should be fine. Profile names shouldn't be with slashes, we'll trust the user about that.
What's wrong with the 2nd commit? Works for me here, otherwise we won't be able to load auth.config from the profile config path. What's your solution to that? We can't use getcurrentdir

**Comment by Ilses** [comment]
@5andr0 I used the / \ replace to dump bots in a subdirectory. Effectively, you can run with:
$> ./xxx.exe bots/profile

**Pull request closed without merging**
