### PR TITLE
WebSocket - Send coordinate with Pokestop event

### PR DESCRIPTION
**Pull request by nicoschmitt**
add gps coordinate to pokestop use

### CODE REVIEW

**Comment by agp89** [comment]
so the pokestops will pop up on your Visualizer? ;-) :+1:

**Comment by timelf123** [comment]
Can you squash this so it doesn't have all the merge-remote stuff?

**Comment by nicoschmitt** [comment]
if I know how to I would... Only the last commit is necessary.

**Comment by timelf123** [comment]
One method, backup last commit 
`git checkout master`
`git checkout -b pokestopcoords`

then
```
git branch -d master
git checkout upstream/master
merge your changes
git push --force
```

**Comment by nicoschmitt** [comment]
error: pathspec 'upstream/master' did not match any file(s) known to git.
Sorry I'm not very good at that...

**Comment by timelf123** [comment]
Amended instructions above to include
```
git remote add upstream git@github.com:NecronomiconCoding/NecroBot.git
fit fetch --all
```

**Comment by nicoschmitt** [comment]
still have an error (another). I'll just drop my fork and recreate it

**Pull request closed without merging**
