### PR TITLE
Sniper improvements and removed spamming debug messages

### PR DESCRIPTION
**Pull request by 5andr0**

### CODE REVIEW

**Comment by Ilses** [comment]
Agreed those messages were overkill for the main client. May or may not have been appropriate for debug.

**Comment by koubie** [comment]
when the new Release version will be released with the updated Snipper?
all the snipping coordinates not working since the morning. Thanks 5andr0 for your awesome works

**Comment by brama23** [comment]
I just want to know the beginner course, if you want to edit PoGo.NecroBot.CLI folder , the folder NecroBot - 0.3.3 , NecroBot - 0.3.3.tar is attached where ? in a release or a folder where ?
because all this time I was wearing only release folder only.
could you please explain where the folder ?

thanks for your answer :)

**Comment by aeryl1999** [comment]
Can necrobot possibly pull sniper spots from say sniping services like http://pokesnipers.com/

**Comment by Nikolaiiiiii** [comment]
Also curious as to when the bot will be released with the updated sniper. Is there anywhere we can get updates?

**Comment by skupfer** [comment]
Today 02:35 @everyone If you want to use it now you have to get the Bot via Source. See Wiki for more information. Next Release is tomorrow.

Compile it yourself. Its working properly so far.

Only think people often mention that the sniper is only using PokeBalls, but not the higher one. It doesn't choose like when it's catching normal pokemon.

**Comment by Ilses** [comment]
@aeryl1999 already done in updated PogoLocationFeeder

That said, this is a PR and not a forum. Please refrain from discussing other topics here.

**Pull request merged**
