### PR TITLE
Added "DelayBetweenLocationUpdate" for every update location, to prevent IP bans on multiple accounts.

### PR DESCRIPTION
**Pull request by ArmsAsuncion**
## Short Description:

Added "DelayBetweenLocationUpdate", so a delay every update location is set to lessen API calls, preventing IP bans when using the bot on multiple accounts simultaneously (Tested 4 accounts, maybe can be used for 5-6 accounts, depending on your config, with 7 seconds delay)

Note: It's a very dirty implementation.

Update: Made some changes to the config to include DelayBetweenLocationUpdate variable.

### CODE REVIEW

**Comment by spamfighter82** [comment]
i love that change, if ppl start whining about that change, could you make at a config variable like setScanDelay or sth along those lines?

**Comment by ArmsAsuncion** [comment]
A config variable can be easily inserted, but less than 7~ wouldn't do much of a help as Niantic's server won't give you data if you scan too fast.

**Comment by sooth** [comment]
Fantastic! I was going to try and implement something like this but work has been very busy.

**Comment by ruchern** [comment]
Awesome stuff. Looks good.

**Comment by ThomasSRL** [comment]
Why the changes in line 35 of PoGo.NecroBot.Logic/Navigation.cs ?

**Comment by ArmsAsuncion** [comment]
@ThomasSRL to account the time you waited. If you waited 7 seconds on each update, you need meters per second * 7 seconds, right? If not, then you'll walk very very slow.

**Comment by ArmsAsuncion** [comment]
untitled

Tested for more than 12 hours now. Using the default settings (7000ms delay), 4 accounts work for more than 3 hours until I closed it to try out 5 accounts. 5 accounts using the same delay caused IP Ban after roughly 15 minutes. However, 5 accounts is feasible using 9000ms delay (as seen at the screenshot)

3 of the accounts are at the same location on Tokyo, while the other 2 is somewhere near where I live (Which isn't in Japan)

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by thecantero** [comment]
pls re-open, would be helpful

**Comment by Unentertained** [comment]
By the time this was removed I was trying to setup git and fetch this PR.
Anyways, I can confirm that this is viable with at least 2 accounts/IP. ~3 hours so far

Although, I was not able to use ArmsAsuncion's exact config. Necrobot deleted the "DelayBetweenLocationUpdate" variable upon login and execution.

**Comment by Oolaruu** [comment]
So this pull request is abandoned ?

**Comment by dfmeier** [comment]
I'm still using this PR with two accounts and only with 2000ms delay and no ban more than 15 hours.

**Comment by spamfighter82** [comment]
any reason why we didn't get this feature?

**Comment by Oolaruu** [comment]
Because there are conflics that need to be solved and @ArmsAsuncion is maybe doing some IRL stuff to not beeing able to come here and fix those conflicts.

**Comment by ArmsAsuncion** [comment]
Sorry, I had to close it due to some problems. If you guys want, I can re-up my git so you guys can compile it yourselves.

**Comment by dfmeier** [comment]
@ArmsAsuncion Thank you I have it already and work flawlessly with 0.8.5.
I wanted to implement your other useful improvement "Added meters check for every Pokemon scan #4460" but it gave me an error when I tried to build. My programmer knowledge is equal to zero so I can't repair it myself.

**Pull request closed without merging**
