### PR TITLE
Fix the hours/minutes not showing correctly

### PR DESCRIPTION
**Pull request by vingesus**

### CODE REVIEW

**Comment by nrmodesto** [comment]
Confirm it's working now with that commit..

**Comment by vingesus** [comment]
Should work, tested it a couple of times, you got any problems? - As far as i know it worked before as well, but then it apperently got changed...

**Comment by nrmodesto** [comment]
It's working without any problem.

**Comment by GamespikeYT** [comment]
is it just me or is the recycling thing also very slow?

**Pull request merged**
