### PR TITLE
Revert I have a problem when I run the programme (ERROR)

### PR DESCRIPTION
**Pull request by Pipperkipper**
aaa

It says PokemonGo.RocketApi.Exceptions.invalidresponseexception was thrown

### CODE REVIEW

**Comment by Pipperkipper** [comment]
I dont know where to post this issue can you tell me?

**Comment by N4MeD** [comment]
Same problem

**Comment by BoomNosloc** [comment]
Having same issue. http://imgur.com/a/yQpcv

**Comment by Gambode** [comment]
same here

**Comment by Gambode** [comment]
maybe server issue

**Comment by erkutalakus** [comment]
server issue. just wait...

**Comment by N4MeD** [comment]
Thanks

**Comment by XtracT** [comment]
Ok, server isue, but if I leave the bot overnight it will not continue because of pressing the key being compulsary. People leave Necrobot overnight, and if servers go down and error occurs, having to press a key keeps the bot from doing its task.

**Comment by lexus82203** [comment]
Yeah, most likely a server issue.

**Comment by igryk** [comment]
Same here.

**Comment by BoomNosloc** [comment]
My only concern is that I able to log in on phone version.

**Comment by N4MeD** [comment]
just change config to "StartupWelcomeDelay": false,

**Comment by tracyadms** [comment]
If you go into the config.json there is this line: `  "StartupWelcomeDelay": true,` setting this value to false will disable the "press key to continue' feature.

**Comment by asantyy** [comment]
Same error here

**Comment by lexus82203** [comment]
it happened randomly to me today.  Just had to close program and restart and ran fine for a hour or so then came w/ the same message. i'm sure its a server issue, or the ban hammer... ;-)

**Comment by asantyy** [comment]
Im still able to login with phone app so it will be not a ban

**Comment by lexus82203** [comment]
I was joking on the ban hammer.

**Comment by ShallowHacker** [comment]
This is so laaaaaaaaame.

**Comment by ChiseTheSlayVega** [comment]
It happens to me when bot tries to approach PokeStop

**Comment by bumblebee851** [comment]
Even though the servers are still up, I'm getting a similar error, but with the lines' numbers moved around...
necrobot_error

**Comment by BigKMama** [comment]
Same here, different line numbers for errors.

Is any of this ran on a Necro server or is this purely communication between google and niantic via our PC's?

crashfile

**Comment by panthernet** [comment]
Chill out, being looked into

**Comment by Zubinexu** [comment]
Is somehow server related

**Comment by voiton** [comment]
Yeah, just came here to say I'm getting this too. Was worried about it being a soft ban because it fails as soon as a pokestop is approached.

**Comment by jtouchstone** [comment]
https://gyazo.com/2360588abf1911e6de9790e88cb5e306

**Comment by crazynever** [comment]
The server is not working properly, so this error will still appear. Hold steady return

**Comment by tn1314** [comment]
changing  "StartupWelcomeDelay": false wont help :( Just gotto wait. They are fixing it

**Comment by BoomNosloc** [comment]
So should we expect it to work properly once servers are working, or would we need to download a fix for it?

**Comment by crazynever** [comment]
Only need to wait for the server returned to work properly; if they want to leave the bot trying to log in can change the setting "StartupWelcomeDelay" to false.

**Comment by BoomNosloc** [comment]
Cool that's what I was wondering if I could leave it running or not.

**Comment by ShallowHacker** [comment]
Yes, I turned StartupWelcomeDelay to false and it repetitively tries to login. As soon as the servers are up, I'll login automatically.

**Comment by ShallowHacker** [comment]
Why is it I can log in on my phone and catch things and it syncs, but I can't login with the bot?
Makes no sense.

**Comment by crazynever** [comment]
Instability ... some people are managing to run normally, while others are facing difficulties; to monitor other sites that use the pokemon api code you see that are in trouble too ... patience my friends ... patience ...

**Comment by ShallowHacker** [comment]
Nah I'm patient I was just confused haha. Thanks for explaining. :)

**Comment by BoomNosloc** [comment]
Anyone still having the errors coming up or is it just me?

**Comment by zhanghaowx** [comment]
I think it's only you. Try the latest version (0.3.3).

**Pull request closed without merging**
