### PR TITLE
[REQUEST] Added option skipping PokeStop hitting

### PR DESCRIPTION
**Pull request by Linewalker**
An option for visiting PokeStops without gaining XP and items.

### CODE REVIEW

**Comment by moredhel92** [comment]
one option to no catch pokemon and only take pokestops?

**Comment by ShawnHardwick** [comment]
I don't understand why you would do this, but like you said, its not hard to implement.

**Comment by junaidd007** [comment]
sorry for writing this here but it keeps showing no snipeabale pokemon found

**Comment by Linewalker** [comment]
As an Idea, I made some changes in the travel logic (not for GPX). I've the feeling, the bot only runs in a circle in a radius of max 1000m all the time.

**Comment by NecronomiconCoding** [comment]
fix conflicts :smile:

**Pull request closed without merging**
