### PR TITLE
Logging of latitude entered by the user

### PR DESCRIPTION
**Pull request by RonaldMariah**
Logging of "longitude" entered by user displays "latitude accepted"

### CODE REVIEW

**Comment by baldmonkey1** [comment]
i am still getting the no usable pokestops found in your area error any help

**Comment by poutros** [comment]
@baldmonkey1 No.

**Comment by baldmonkey1** [comment]
@poutros even u r not able to use the bot?

**Comment by poutros** [comment]
Noone is!!! Here: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d63g28s

**Pull request merged**
