### PR TITLE
Disable bots

### PR DESCRIPTION
**Pull request by colinodell**

### CODE REVIEW

**Comment by colinodell** [comment]
https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Comment by NoiRequiem** [comment]
Is Necrobot down?

**Comment by blue1Elephant** [comment]
Yes

**Comment by cheah0105** [comment]
Would it be up again?

**Comment by SpectrumWolf** [comment]
Have boots will not be used again?

**Comment by blue1Elephant** [comment]
read the readme

**Comment by AlexisjrFreitas** [comment]
Please we need you Necrobot :(

**Comment by oxidoex** [comment]
Bot is not down, just developments have been ceased isn't it?

**Comment by tggiml** [comment]
is was pleasure to meet you guys, had a lot of fun... Sadly, it was our Judgement DAY. 
hope to see you again!

**Comment by colinodell** [comment]
The bot will continue working, but Niantic seems to be detecting bots and issuing both soft- and hard-bans.

**Comment by SpectrumWolf** [comment]
ahh ok.. Bot is working, but risk banned.

**Comment by cheah0105** [comment]
@colinodell Are you trying to tell us that Necrobot is hiding from Niantic? Thats why all the release ZIP files are gone..

**Comment by blue1Elephant** [comment]
@cheah0105 Read the Readme on the frontpage

**Comment by Cyrus-Wong** [comment]
the is discord channel been taken down?

**Comment by diabloloy** [comment]
Hey guys ! First id' like to thank you for the wonderful job that is the Necrobot. We all understand why is Niantic is pushing forward to shut down all the bots in the market, since the game is currently a korean grind with no other attractives. 

You guys who develop it have been saving our lives, especially the ones who work a lot and don't have time play the game properly and still be somewhat competitive.

May I ask if you guys intend to make a new release soon , or are you shutting it down for good ?

Thank you for all you have provided us.

**Comment by K1llercat** [comment]
A pity... oh well, maybe its for the better. Thank you for your great work (to all who made the bots, API and stuff)

Maybe you could just do Info tool. It was cool seeing the IV Values to compare ^^'

**Comment by zzzz9999** [comment]
If we compile sources, will bot work?

**Comment by Cyrus-Wong** [comment]
@zzzz9999 why not just use the released 0.8.6

**Comment by zzzz9999** [comment]
where can I get NecroBot-master.zip for 0.8.6? please ...

**Comment by Cyrus-Wong** [comment]
@zzzz9999 cannot talk much here, view my github profile.

**Comment by gianlu696** [comment]
http://gopokemongo-download.com/necrobot-for-pokemon-go/ YOU CAN DOWNLOAD HERE

**Comment by K1llercat** [comment]
Ofc someone could compile the old scripts, but you would be better advised not to use any bots atm. Niantic is going apeshit atm. So the risk getting a REAL permaban is more likely now

**Comment by The-Titan** [comment]
please delete this conversation so niantic doesnt see this ;)

**Comment by Skolzack** [comment]
Niantic developers are spying us here and you guys still posting these links.. fuck off

**Comment by zzzz9999** [comment]
@The-Titan I needed the sources

**Comment by bambangweb** [comment]
i can catch pokemon but cant loot pokestop...this is soft or hard banned?

**Comment by ausscheider** [comment]
Hello everyone,

No Panik. It's no ban all bot User. Niantic have Problems with the Server. I Hope necrobot come back, because it's a Great work.
Best wishes and regards from germany

**Comment by Skolzack** [comment]
@bambangweb A new type of softban, we can call it "hardban" because Niantic improved the time of the softban I think.. More than 12hours and i'm still hardbanned, can catch pokemons but cant loot pokestops

**Comment by ddo001** [comment]
@ausscheider Any proof？

**Comment by diester** [comment]
message written on 08/12 20:00 on the saturated server I think they are doing something about the game. I can catch pokemon but all pokestop say "try again later"

**Comment by dibudabu** [comment]
@Skolzack I've got a problem similar to yours. I can get items from pokestops but i can't catch pokemon!!

**Comment by diester** [comment]
@Cyrus-Wong Finally there is nothing I find nothing

**Comment by DheekeyCarey** [comment]
I can still use the bot

**Comment by jikifreaky** [comment]
@Skolzack I cannot catch pokemon at all either... but i get get shit from pokestops which is weird. If anyone has figured out how to bypass this ban please let me know! Thanks! 

To the people who made NecroBot Thank you for all the hard work and effort you guys put into this! loved watching it run!

**Comment by tatejensen6** [comment]
Thank you necrobot you got me all my amazing Pokémon couldn't be good in this game without you!

**Comment by NecronomiconCoding** [comment]
Thanks guys :heart:

**Comment by osmankudu** [comment]
thank you necrobot

**Comment by yanghaa** [comment]
What a pity！THANKS for all contributers

**Comment by DheekeyCarey** [comment]
untitled

**Comment by mpimentel1** [comment]
Your ta working?

**Comment by mpimentel1** [comment]
Necro was back to work?

**Comment by DheekeyCarey** [comment]
It's working the whole day for me

**Comment by mpimentel1** [comment]
sem titulo

**Comment by bambangweb** [comment]
damn....i open again my id but writen failed to get game data from the server...
this mean perma banned?
because i open my id one hour ago still can go to game just cant loot pokestop...
OMG

**Comment by diester** [comment]
@mpimentel1 I have the same problem though:  http://ispokemongodownornot.com/

all it's ok   :(   i am lost

**Comment by zzzz9999** [comment]
So, anyone with NecroBot-master.zip from v0.8.6 ?

**Comment by diester** [comment]
I seek and not find :(

**Comment by zzzz9999** [comment]
I found it!

**Comment by diester** [comment]
I found I will try

**Comment by zzzz9999** [comment]
bot still working.
how can I know my Pokemon Inventory size?

**Comment by diester** [comment]
@zzzz9999  look in the config file

**Comment by zzzz9999** [comment]
thanks for reply. which parameter?
also, in console cannot see that info: Number of Pokemon on Inventory.

**Comment by diester** [comment]
go in config.js

**Comment by zzzz9999** [comment]
yes im looking into it

**Comment by bambangweb** [comment]
can u share it bro?

**Comment by diester** [comment]
after first start, creation of config file and in it there is the file config.js

**Comment by diester** [comment]
@bambangweb I can not put it here :( too risky

**Comment by zzzz9999** [comment]
I think you don't understand my question: where can I see my current Pokemon Inventory? The amount of Pokemon I have.

**Comment by diabloloy** [comment]
@zzzz9999 , If you use the option to evolveallpokemon with enough candy alongside the option to only start evolving after x% of your pokemon inventory, each time the bot captures a pidgey for example, it will tell you how many more it needs to capture before start the evolving process. The full inventory is 250 by default. So the first number you see on this report will be the current ammount of pokemon in your inv

Additionally, could you pls pm me with the link to the 0.8.6 release ? thanks

**Comment by diester** [comment]
@zzzz9999  like the other at the beginning

[url=http://www.hostingpics.net/viewer.php?id=694348listpokeinven.png][img]http://img4.hostingpics.net/thumbs/mini_694348listpokeinven.png[/img][/url]

**Comment by bambangweb** [comment]
i got it...u sure still work?

**Comment by zzzz9999** [comment]
Still not a clear information, current Inventory.
Well github no longer have messaging system between users ...

**Comment by diester** [comment]
@diabloloy  I do not know send an pm on github

@bambangweb yes but I do not know what risk taking is the use

**Comment by bambangweb** [comment]
i try but necrobot stop working...any solution?

**Comment by diabloloy** [comment]
@zzzz9999 the bot doesn't show you how many pokemon you currently have, unless you set these options on:

"EvolveAllPokemonWithEnoughCandy": true,
 "EvolveKeptPokemonsAtStorageUsagePercentage": 100.0,

Everytime it captures a pokemon on the "Pokemon to evolve list", it will report your current pokemon inventory

. 

Is there anyway you could share the 0.8.6 release ? just quickyl put it here and please delete ?

**Comment by diester** [comment]
@bambangweb 28 minutes it works for me but I do not know for how long

**Comment by diabloloy** [comment]
@diester can you please post a link to it ? maybe on your page ?

**Comment by bambangweb** [comment]
u change config?because i cant start that necrobot 8.6

**Comment by diester** [comment]
@bambangweb yes I made simple modification with the .exe this has created the config folder where I put my things as other Version

@diabloloy provides a quick simple email

**Comment by bambangweb** [comment]
i seee....let me try

**Comment by diabloloy** [comment]
@diester thanks, man. 

Please send it to eduaugusto.rocha2@gmail.com.

Can I use my old config.js or do i have to manually change everything back from your archive ?

**Comment by diester** [comment]
@bambangweb   errase plz

**Comment by zzzz9999** [comment]
http://xvm-mod.com/wp-content/uploads/2016/08/Release_0_8_6.zip

**Comment by zzzz9999** [comment]
removing in 15 seconds

**Comment by diabloloy** [comment]
delete the comment please. I'm reaching out the link. tks

**Comment by diester** [comment]
@diabloloy delete your mail and look in

**Comment by zzzz9999** [comment]
if its not working, that's because account is currently flagged/banned.

**Comment by zzzz9999** [comment]
did you saw the link?

**Comment by diester** [comment]
@zzzz9999 seriously  ....................................... :(

**Comment by zzzz9999** [comment]
what? didnt understand

**Comment by diester** [comment]
@ zzzz9999 sérieusement ....................................... :(  --------------- > pour l' interdiction?

**Comment by zzzz9999** [comment]
test it. mine is working, currently playing in japan lol 15K xp/h

**Comment by zzzz9999** [comment]
slow speed ;)

**Comment by diester** [comment]
@zzzz9999  in japan........................... lol

**Comment by zzzz9999** [comment]
im removing all my comments in a few mins

**Comment by ryannguyen100** [comment]
Can you send me a link to ryannguyen100@gmail.com
Pls
Thanks you very much

**Comment by zzzz9999** [comment]
sure

**Comment by zzzz9999** [comment]
delete email address

**Comment by diester** [comment]
@zzzz9999 erase your messages

**Comment by diabloloy** [comment]
thanks @zzzz9999 and @diester . Thank you both very much !

**Comment by zzzz9999** [comment]
ryannguyen100 delete message

**Comment by diester** [comment]
@diabloloy erase your messages too

**Comment by diabloloy** [comment]
@diester i believe i deleted eveything. I'm still having trouble to launch it. it fails immeadiatly

**Comment by diester** [comment]
config.exe open. do basic adjustment then go to the folder with the exe create config and make the adjustment with notepad ++

**Comment by FirasJ** [comment]
try with AutoUpdate=false

**Comment by ausscheider** [comment]
v 0.8.5 works perfect with bot visualizer and location feeder

**Comment by ausscheider** [comment]
http://uploaded.net/file/vwlpgbyf  <-- Version 0.8.6

**Comment by diabloloy** [comment]
still having the same rocket api error :(

**Comment by ausscheider** [comment]
v 0.8.6 works perfect too

**Comment by TomPK** [comment]
Failed to get data from this serve, someone know what is? Ban permanent? link to more informations about bans? thansk

**Comment by MrPiwy** [comment]
well, just delete this conversation please.

**Comment by The-Titan** [comment]
It means permanent ban i have it too :P

**Comment by DheekeyCarey** [comment]
are you guys still encoutering the problem coz I am testing it right now and it works all fine

**Comment by jikifreaky** [comment]
@DheekeyCarey yes I'm still having the problem

**Comment by DheekeyCarey** [comment]
I don't know what's going on but it works all good over here

**Comment by diester** [comment]
the banishment of the account is active (not just by the ip) so be careful !!!!

**Comment by Cyrus-Wong** [comment]
my catch flee wasgone yesterday, but still cannot login normally, must login ptc 1st, log out just can login my gmail main acc.... dangerous

**Comment by ItsOnlyMeNL** [comment]
Necrobot screwed us over.. obvious thing to get banned on the exact same dat when necrobot shuts down.  My other bot account that has not been using Necrobot still works.

Well played!

**Comment by NecronomiconCoding** [comment]
Where did I screw you guys over? @ItsOnlyMeNL the bans were not even noticed by us before the shutdown. Also those were temp Bans that lasted much longer. All other Bot Developers like PokeFarmer, PokeMobCopy etc had detections too.

**Comment by lostgecko** [comment]
No one@Necrobot has screwed anyone over. It's a bot a tool used to cheat and lvl up your toons. I was banned aswell but it was a temp ban also i wasn't running multiple bots. In any game pc or otherwise if you are running a farm bot,lvling bot that goes against their eula you run the risk of being banned. Just make a new acct and start over the bot they provided was free you had the option not to dl right? Sorry for the rant necrobot devs I just don't see how anyone being banned is your fault you all did a stupenise job in my book.

**Comment by lostgecko** [comment]
Stupendous*

**Comment by ItsOnlyMeNL** [comment]
@NecronomiconCoding it's just strange looking from my point of view. I have been using a other bot for a long time with no problems at all. In fact my other bot account is still running on that one.  

I've been using Necrobot for less then a day, then you guys delete all the files and next thing i know is that the account is banned that has used this bot.  And i know, their are risks on it of using bots/cheating etc, but still.  Only because i used this bot for less then a day and you guys stop and delete all the files + account gets banned few hours later is just giving me this strange feeling to it. Kinda comes over to me like selling the player names of who has been using it. Since we are not able to start the bot because all the files are gone its possible to log the usernames logging in. 

If that ain't true then sorry for the first reply.

**Comment by diester** [comment]
necrobot still works when I write. Bypass system does not work every time but has after all depends on the adjustment made in the config file.

the problem is not the type of bot you use but the configuration you made (movement speed, teleportation from one continent to another in minutes, number of candy and possess lvl pokemon).

Niantic implements system fraud, nothing more logical. the question that ultimately arises is that the majority of people using bots, they will continue to play normally legitimately? The answer is no

sorry for my English I use a translator

**Comment by NecronomiconCoding** [comment]
@ItsOnlyMeNL feel free to check the source existing in one of the 2,5k forks. Maybe you will find us collecting player names :lollipop:

**Comment by DheekeyCarey** [comment]
still working hella fine!
untitled

**Comment by diester** [comment]
@DheekeyCarey do not you worried as you will ban all persons who use an application (API). Niantic clearly communicate on the account made  made that all who use a aplication api its permanent ban (pokevisor, bot, or other).

we plan to set up the exchange system and arena pvp so it wants a player between equity

**Comment by Cyrus-Wong** [comment]
all my bot accounts, all my friend who botted, and some of them stop botted even before the new softban implemented, all accounts already perma ban == cannot login at all no matter what, cannot get data from server. Hell gg.

**Comment by jikifreaky** [comment]
If you guys would still like to use a bot try using pokemon go bot - gotta catch em all (Google it). You will need visual studios. You will also need to visit there discord to get the encryption file. You will need to put the encryption file in the debug folder. Pokemon.rocket.api.console.>bin>debug. Also to get the debug folder to show up you need to open pokemongo.rocketapi. then close it and the debug folder should appear. Once you put the encryption file in the debug folder open the program back up and click on settings under pokemongo.ricketapi.console and click on the settings with what looks like a gear wheel next to it. And change your settings.now click on file and save settings.settings. Now right click on pokemongo.rocketapi.console and click on start as new project. Than once you've done that hit crtl+F5 and it will launch a cmd screen similar to necrobots. IF YOU WANT TO CHANGE YOUR SETTINGS AFTER YOU'VE RUN THIS YOU NEED TO GO INTO POKEMONGO.ROCKETAPI.CONSOLE>BIN>DEBUG>SETTINGS. TO CHANGE COORDS DELETE THE LAST COORDS.INI FILE AND THAN CHANGE THEM IN THE SETTINGS WHICH CAN BE EDITED WITH NOTEPAD OR NOTEPAD++ ALSO THIS IS WHERE YOU CAN CHANGE WHICH ACCOUNT YOU WISH TO USE!

**Pull request closed without merging**
