### PR TITLE
Softban bypass FIX - with checks.

### PR DESCRIPTION
**Pull request by TheBorna**
Softban bypass here works without issues, it checks if the pokestop is looted + tries first 5 times.

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
please fix the conflicts. waiting on you to push new release

**Comment by panthernet** [comment]
Were looking to change this also :D Nice work.

**Comment by Hardell** [comment]
You don't reset TimesZeroXPawarded when you get XP again.

**Comment by NecronomiconCoding** [comment]
@Hardell https://github.com/NecronomiconCoding/NecroBot/commit/c13b5866eed5592c7e723aca50bcf141747865ab

**Comment by mich3lam** [comment]
@TheBorna thank you!

**Comment by Hardell** [comment]
@NecronomiconCoding it was overwritten in the merge. Now it keep increasing it forever again.

**Comment by NecronomiconCoding** [comment]
@Hardell better now ?

**Pull request merged**
