### PR TITLE
Write location to disk on update

### PR DESCRIPTION
**Pull request by jessewhite007**
prevent soft bans when default location is too far away from last location
change read location of coordinates to config where everything else lives

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
can you please rename from Coords.ini to LastPos.ini

**Comment by jessewhite007** [comment]
Done

**Comment by actislav** [comment]
maybe i am wrong, but that code does not prevent, just warn

**Comment by jessewhite007** [comment]
Good point, I could either throw an exception or just set to last position.

**Comment by Rawrlex** [comment]
Working with .gpx too?

**Comment by jessewhite007** [comment]
@Rawrlex yes it works with .gpx too.

**Pull request merged**
