### PR TITLE
Log Pokemon stats

### PR DESCRIPTION
**Pull request by DilatoryCheetah**
Output Pokemon Lvl, CP, and IV [attack/defense/stamina] in log file

### CODE REVIEW

**Comment by trana315** [comment]
output this in separate log file, allpokeslog.txt?

**Comment by DilatoryCheetah** [comment]
I could do that, but them I would have to overload Logger.Log with a filename parameter.  Is it that important to have it in a separate file?  It's pretty easy to scan log.txt to find the output.  However, I'll do whatever people think is best

**Comment by pattythesleeper** [comment]
As @trana315 sayed it would be great if it could output in spearate log file :)

**Comment by DilatoryCheetah** [comment]
Ok, modified code to output to allpokeslog.txt

**Comment by PocketMobsters** [comment]
Conflicts must be resolved, please resubmit your pull request with the conflicts fixed.

**Comment by DilatoryCheetah** [comment]
Resubmitted as pull request 395

**Pull request closed without merging**
