### PR TITLE
Added ability to view candies on Catch

### PR DESCRIPTION
**Pull request by doggiekuk**
Due to the lack of updating candies after catches, this is still a bit glitchy.

Anyone can improve please.

### CODE REVIEW

**Comment by roteak** [comment]
Tested and working.

Calculates correctly after Catch and Transfers.

http://i.imgur.com/yHLmQcM.png

**Comment by JoshYuen** [comment]
I feel like the info should be on transfers not catch. Because it should increment on transfer and then you can see new total. I think the catch log is already long enough and we are basically making it longer.

Any others want ot throw in some input?

**Comment by JoshYuen** [comment]
PR #468 has similar logic maybe there should be a collaboration to merge the two PRs into 1.

**Comment by yamashi** [comment]
Master is deprecated.

**Pull request closed without merging**
