### PR TITLE
Fix Incense Pokemon Catch Task

### PR DESCRIPTION
**Pull request by emoisback**
Fix error when catch incense pokemon, fortdata is null.

### CODE REVIEW

**Comment by myo** [comment]
nice find

**Comment by csutcliff** [comment]
This fix (along with some improvements) has been PR'ed a number of times over the last few days, never merged. I don't think they are interested!

**Comment by panthernet** [comment]
Too much pulls & issue reports for small open-source team to handle effectively. Have to live with it.

**Comment by NecronomiconCoding** [comment]
@csutcliff there you go.

**Comment by csutcliff** [comment]
thanks! :+1:

**Comment by Ilses** [comment]
FML I'd submitted this fix three times. Thanks for helping push this through.

**Pull request merged**
