### PR TITLE
Major Issue (PokemonsToIgnore, PokemonsToEvolve, PokemonsNotToTransfer Fix)

### PR DESCRIPTION
**Pull request by simplyblue333**
[config2.txt](https://github.com/NecronomiconCoding/NecroBot/files/389771/config2.txt)

I kept wondering why specific pokemon weren't following these rules, 
than when I was exploring the pokesniper, I decided to add more creatures to the config to more successfully sniper more breeds of poke's. List went:
lowercase2
Noticed the bot would run this error:
lowercase1

Basically in conclusion when I Capatalized the Pokename's the bot would detect them.
For reason this bot is case-sensitive, which might explain why default lower-cased configs won't ignore, evolve, transfer specific creatures/

Updated config list:
{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": ,
  "DefaultLongitude": ,
  "DelayBetweenPokemonCatch": 2000,
  "DelayBetweenPlayerActions": 2000,
  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseEggIncubators": true,
  "DumpPokemonStats": false,
  "GpxFile": "GPXPath.GPX",
  "UseGpxPathing": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "MaxTravelDistanceInMeters": 1300,
  "KeepMinCp": 1600,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "PrioritizeIvOverCp": true,
  "RenameAboveIv": true,
  "RenameTemplate": "{0}_{1}",
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": true,
  "SnipeAtPokestops": true,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 10
    },
    {
      "Key": "itemHyperPotion",
      "Value": 40
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "Aerodactyl",
    "Venusaur",
    "Charizard",
    "Blastoise",
    "Nidoqueen",
    "Nidoking",
    "Clefable",
    "Vileplume",
    "Arcanine",
    "Poliwrath",
    "Machamp",
    "Victreebel",
    "Golem",
    "Slowbro",
    "Farfetchd",
    "Muk",
    "Exeggutor",
    "Lickitung",
    "Chansey",
    "Kangaskhan",
    "MrMime",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dragonite",
    "Mewtwo",
    "Mew"
  ],
  "PokemonsToEvolve": [
    "Caterpie",
    "Weedle",
    "Pidgey",
    "Rattata",
    "Spearow",
    "Zubat",
    "Doduo",
    "Goldeen",
    "Paras",
    "Ekans",
    "Staryu",
    "Psyduck",
    "Krabby",
    "Venonat"
  ],
  "PokemonsToIgnore": [
    "Caterpie",
    "Weedle",
    "Pidgey",
    "Rattata",
    "Spearow",
    "Zubat",
    "Doduo"
  ],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Zubat": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Pinsir": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golduck": {
      "KeepMinCp": 1350,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Tentacruel": {
      "KeepMinCp": 1350,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Starmie": {
      "KeepMinCp": 1350,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 750,
      "KeepMinIvPercentage": 92.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Gyarados": {
      "KeepMinCp": 1200,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 5
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "Dratini",
      "Magikarp",
      "Eevee",
      "Charmander",
      "Charmeleon",
      "Wartortle",
      "Ivysaur",
      "Bulbasaur",
      "Dragonair",
      "Aerodactyl",
      "Venusaur",
      "Charizard",
      "Blastoise",
      "Nidoqueen",
      "Nidoking",
      "Clefable",
      "Vileplume",
      "Arcanine",
      "Poliwrath",
      "Machamp",
      "Victreebel",
      "Golem",
      "Slowbro",
      "Farfetchd",
      "Muk",
      "Exeggutor",
      "Lickitung",
      "Chansey",
      "Kangaskhan",
      "MrMime",
      "Gyarados",
      "Lapras",
      "Ditto",
      "Vaporeon",
      "Jolteon",
      "Flareon",
      "Porygon",
      "Snorlax",
      "Articuno",
      "Zapdos",
      "Moltres",
      "Dragonite",
      "Mewtwo",
      "Mew"
    ]
  }
}
Please note: no co-ordanites, "DelayBetweenPlayerActions" is default 5000, and new "WalkingSpeedInKilometerPerHour"default is 15.0 but farms slower and with the new unsoftban bot I am not at all worried.

P.S. You will capture many more bulbasaurs when sniping, and God knows what else (missingno!) (I probably should've kept quiet, but this community is great.) PUT COMMA'S AROUND YOUR AUTH USERNAME AND PASSWORD, jeez people.. still love you lazy bastards :D

### CODE REVIEW

**Comment by simplyblue333** [comment]
New config already paying off:
[22:22:29] (PKMN) (CatchSuccess) | (Normal) Ivysaur Lvl: 21 CP: (843/979) IV: 52.00% | Chance: 6.53% | 15579736.61m dist | with a PokeBall (2 left). | Candies: 50
Shweeet!

**Comment by dartmagus** [comment]
I put pokemon to ignore 

"PokemonsToIgnore": [
    "Caterpie",
    "Weedle",
    "Pidgey",
    "Rattata",
    "Spearow",
    "Zubat",
    "Doduo"

But when it starts it change to lowers... and keep catching them.

Somebody know how solve this?

**Comment by Kuroah** [comment]
My bot stops working every 30 minutes. Anyone can help me fix it?

**Comment by simplyblue333** [comment]
@Kuroah error?

@dartmagus 
zubat is in the pokemon keep:
"Zubat": {
"KeepMinCp": 500,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 2

delete that
and make sure you're keep duplicate is off and keep your keepmincp high

**Comment by Kuroah** [comment]
@simplyblue333 There is no error message. The bot just simply stops processing (no new information shows in the window). I have to close the program and restart it again every 30 minutes.

**Comment by simplyblue333** [comment]
@Kuroah 
I just had the same issue an hour ago and was worried it wouldn't run overnight.
Turn "StartupWelcomeDelay": false
and it will run normally again

**Comment by Kuroah** [comment]
@simplyblue333 I have "StartupWelcomeDelay" turned off already, but it still stops when the timer hits "00.00.30:03". Below is my config. I am worried it won't run overnight still...

{
  "AmountOfPokemonToDisplayOnStart": 50,
  "AutoUpdate": true,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 37.808576,
  "DefaultLongitude": -122.409836,
  "DelayBetweenPokemonCatch": 1000,
  "DelayBetweenPlayerActions": 1000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseEggIncubators": true,
  "DumpPokemonStats": false,
  "GpxFile": "GPXPath.GPX",
  "UseGpxPathing": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "MaxTravelDistanceInMeters": 500,
  "KeepMinCp": 1777,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 94.9,
  "KeepPokemonsThatCanEvolve": false,
  "PrioritizeIvOverCp": true,
  "RenameAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "SnipeAtPokestops": true,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 50
    },
    {
      "Key": "itemGreatBall",
      "Value": 200
    },
    {
      "Key": "itemUltraBall",
      "Value": 500
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 10
    },
    {
      "Key": "itemMaxPotion",
      "Value": 50
    },
    {
      "Key": "itemRevive",
      "Value": 0
    },
    {
      "Key": "itemMaxRevive",
      "Value": 10
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 100
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "aerodactyl",
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo",
    "goldeen",
    "paras",
    "ekans",
    "staryu",
    "psyduck",
    "krabby",
    "venonat"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1777,
      "KeepMinIvPercentage": 97.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1777,
      "KeepMinIvPercentage": 97.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Zubat": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 99.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Golbat": {
      "KeepMinCp": 1777,
      "KeepMinIvPercentage": 97.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pinsir": {
      "KeepMinCp": 1777,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Golduck": {
      "KeepMinCp": 1777,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Tentacruel": {
      "KeepMinCp": 1777,
      "KeepMinIvPercentage": 97.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Starmie": {
      "KeepMinCp": 1777,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Eevee": {
      "KeepMinCp": 850,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Dratini": {
      "KeepMinCp": 850,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Dragonair": {
      "KeepMinCp": 1350,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "Dratini",
      "Eevee",
      "Snorlax",
      "Lapras",
      "Vaporeon",
      "Dragonite",
      "Charmander"
    ]
  }
}

**Comment by simplyblue333** [comment]
@Kuroah, do you have a google account? Possibly needing a refresh token? I am running my friends google accnt but it doesn't shut off every 30 min and there are no immediate errors in your config.

I would delete, redownload and reconfigure adding a refresh token (if you have one from the past).

**Comment by sliverfishes** [comment]
Maybe add Tauros too for the non-NA folks.

**Comment by Kuroah** [comment]
@simplyblue333 Thanks! I just realize my google refresh token is "null". Can i simply copy and paste google refresh token from my past config to this new one? If I lost my past file unexpectedly, how I can I get my google refresh token?

**Comment by xXxhp** [comment]
@sliverfishes same problem but with ptc acc :/

**Comment by simplyblue333** [comment]
@Kuroah, you can add the old refresh token should still work, if it doesn't find an old version of necrobot and preset a config.json before launching the app and set "AutoUpdate": false since it will not give you a token in the new versions.

**Comment by matatian** [comment]
because my duplicate Pokemon are not transferred ?
a
{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.785091,
  "DefaultLongitude": -73.968285,
  "DelayBetweenPokemonCatch": 2000,
  "DelayBetweenPlayerActions": 2000,
  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseEggIncubators": true,
  "DumpPokemonStats": false,
  "GpxFile": "GPXPath.GPX",
  "UseGpxPathing": false,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxTravelDistanceInMeters": 1000,
  "KeepMinCp": 1777,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 0.0,
  "KeepPokemonsThatCanEvolve": false,
  "PrioritizeIvOverCp": false,
  "RenameAboveIv": false,
  "RenameTemplate": "{0}_{1}",
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": true,
  "SnipeAtPokestops": true,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 10
    },
    {
      "Key": "itemHyperPotion",
      "Value": 40
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "aerodactyl",
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo",
    "goldeen",
    "paras",
    "ekans",
    "staryu",
    "psyduck",
    "krabby",
    "venonat"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": null,
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "Dratini",
      "Magikarp",
      "Eevee",
      "Charmander"
    ]
  }
}

**Comment by simplyblue333** [comment]
@matatian  
"KeepMinIvPercentage": 0.0,
You are keeping every pokemon you capture, make this:
"KeepMinIvPercentage": 90.0,

**Comment by orangesuave** [comment]
@simplyblue333  @matatian has PrioritizeIvOverCp = false so the 0 iv percentage shouldn't make a difference with such a high CP value. This is certainly something worth looking into. (Transfer bugs are the worst as all your bot's hard work may not pay off post run!)

**Comment by orangesuave** [comment]
To those with the other random errors, triple check your config and auth files. 

For PTC logics, the Auth type is "ptc" case sensitive. Also I found that having a fake google account listed helped with constant authentication related errors. (Even when using ptc as the auth type).

**Comment by StrikeNine** [comment]
Whenever I run the bot, my corrected Config. reverts back to the lower case PokemonID's. How do I make the capitalization edits permanent?

**Comment by KicksDNA** [comment]
Is there any way to keep old auth and config files when the bot auto updates??

**Comment by StrikeNine** [comment]
yes just save a copy of the auth and config files outside of the bot folder

**Comment by KicksDNA** [comment]
@StrikeNine kinda annoying when you're running 50+ accounts...wish it could just leave those two files untouched when updating

**Comment by FrcAndroid** [comment]
Hey can I know how do you guys make this work? I have all the config of the first post (simplyblue333), but I keep getting a bunch of rattata/zubat/pidgey captured and I run into this quite a lot
[Image](http://i.imgur.com/VAIoAIZ.png)

Thing is getting rid of all this "clutter" (because despite what config says, they don't get evolved at all or anything, they are just making space) is really tedious to do on phone due to shitty performance of the program itself, something as simple as  tapping the pokemon, sliding down, and transferring can take half a minute. Why the functions aren't properly working? I've seen above it's supposed to transfer the mons when it's full.

**Comment by Yodude12** [comment]
Yo guys anyone has figured how to keep alot of pokeballs before catching pokémons I keep getting no pokebalss and some pokémons has escaped I just  lost charmelion

**Comment by Shibby7986** [comment]
@Yodude12 you can configure the minimum balls to not transfer in the config set a larger buffer.
look under transfer filter

**Comment by Shibby7986** [comment]
@orangesuave From what I can tell the IV percentage keep is independent to the transfer priority
i.e if it meets the iv it won't be transferred regardless.
so say it was set to 90 and you got 3 90+ IVs of the same mon it keeps them all.
but new mons will less than 90 will be prioritised by cp/iv as per your config.

**Comment by Yodude12** [comment]
@Shibby7986 ok thanks i will try it !!

**Comment by Shushii** [comment]
I'm having an issue where every time I run the bot, Pokemon's names keep reverting from capitalized to to lowercase in my config. I'm pretty sure the bot is case-sensitive too, so all the filters aren't working besides Sniping. The Pokemon names don't change their capitalization there for some reason.
Does anyone know how to fix this?

@StrikeNine
@dartmagus

**Pull request closed without merging**
