### PR TITLE
Update Inventory.cs

### PR DESCRIPTION
**Pull request by qwikwit**

### CODE REVIEW

**Comment by PocketMobsters** [comment]
You added a comment.. That I removed... I see we are at odds here.

**Comment by TheCrimsonDevil** [comment]
For future reference, do you want us to comment our code or leave it blank? I'd prefer commented, but I could see it really getting out of hand with some people.

**Comment by PocketMobsters** [comment]
If you'd like to comment your code that's fine, anything excessive will probably get removed. I'd prefer light comments over nothing, just a "hey this is why i did this" would be fine.

**Comment by ilu01** [comment]
@PocketMobsters But isn't this a valuable and short comment as you expect it?

**Pull request closed without merging**
