### PR TITLE
Exception .. cannot get rid of it. Totally stuck :/

### PR DESCRIPTION
**Pull request by Mikkele0815**
[01:51:37] Program will continue after the key press...
[01:51:39] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__19.MoveNext() in D:\Dev\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 251
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__12.MoveNext() in D:\Dev\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__0.MoveNext() in D:\Dev\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 15
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 34
[01:51:39] Logging in using Ptc

I'm trying to get rid of that exception, but I don#t see my mistake. Anybody knows a solution?

### CODE REVIEW

**Comment by nunocaires** [comment]
fix those paths.. make it ./ and not in D:\dev..

**Comment by asantyy** [comment]
Yep same me "The pokemon go servers are having a bad time. Chill out"

**Comment by asantyy** [comment]
Works again! Good job!

**Comment by orangesuave** [comment]
Any ideas for these? I've tried two different builds and get these on each (including the latest commit)

error


error2

**Comment by newbiesers** [comment]
untitled
updated 0.3.2
login via Ptc/goole crashed like that,
anyone can help me

**Comment by Mikkele0815** [comment]
@newbiesers: did you write your accountname and password under the use of quotation marks?

**Comment by Mikkele0815** [comment]
@AustinAmighty: Every time, you start the exe, the program checks, if there is a new version and downloads it for you. No need to manually download it each time, there was an update.

**Comment by orangesuave** [comment]
@Mikkele0815 yes indeed! Both for Google and Ptc. Same error.

**Pull request closed without merging**
