### PR TITLE
Timed Restart Setting

### PR DESCRIPTION
**Pull request by scristall**
This pull request adds a configuration variable to optionally restart the bot after N minutes.  This is to alleviate the need for wrapper scripts.

I would also like to potentially record the last GPS location, and set that as the restart's GPS location.

### CODE REVIEW

**Comment by jkoeb8762** [comment]
Issue/ something I noticed.... If u record the last GPS location & restart there... what happens to the GPX file??

**Comment by scristall** [comment]
Sorry, I didn't actually implement that, but I'd like to potentially add it since it's an advantage of having it reset itself.

This PR simply adds a reset timer.

**Comment by jkoeb8762** [comment]
cool! I honestly have close to no idea about how the bot functions and what does what.... 
so... REALLY APPRECIATE the help! :)

**Comment by rammydesi** [comment]
after relogin its ask to press the key to confirm that locations are correct or not, which kills the purpose of bot, i have to check the bot in evry 15-20 mins that its stuck or not, please remove pressing key confirmation and add auto execute after certain time

**Comment by nas-** [comment]
@rammydesi I understand it can be hard, but have you ever tough to have a look to the config instead of asking for changes? Just go there and set  StartupWelcomeDelay  to false to avoid having to press anything when the bot starts

**Comment by rammydesi** [comment]
@nas just realised after posting the comment, sorry for not deleting it afterwards, thanks anyways nas :)

**Comment by chronosz** [comment]
Is there a fix yet for the " stops working after 30 minutes " except for the bat file.

**Comment by Rozzla** [comment]
FIX :

Go to the folder nammed "config" and open "config.json" and go to >> "StartupWelcomeDelay": false, (if it's true, change to false)

and put this script in the main folder and lauch "autorestart" :

https://mega.nz/#!gs8yQTDL!UXw7rhdcdw8lQT9khDvwVN9D5MzzjVeJiBVgE0gFGek
(The script exit the bot after 30mn and wait 4mn, and execute again the bot for 30mn)
(V.0.2)

**Comment by bobbelalle** [comment]
i put the .bat file into the folder but it says "unable to find necrobot.exe"

**Comment by Shibby7986** [comment]
@bobbelalle 
That's strange it should work fine.
make sure u put the .bat in the same folder as your necrobot.exe

**Comment by ShawnHardwick** [comment]
This was fixed in 0.3.3.

**Pull request closed without merging**
