### PR TITLE
Add indonesia translation file

### PR DESCRIPTION
**Pull request by hendrawd**

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
please now include into .csproj

**Comment by hendrawd** [comment]
Is that enough? Actually i have only little experience with C#

**Comment by panthernet** [comment]
Yes, that's enough. Please update lang file with newly added translations. Thank you,

**Comment by hendrawd** [comment]
@panthernet lang file here is translation.id.json right? Can you give a hint where is the newly added translations path? Actually i translate it from translation.en.json, but i didn't find it on the project, but only from release

**Comment by clicknetcafe** [comment]
newly added Indonesia translations

https://gist.github.com/clicknetcafe/b92393e590ae3157cf49242cb6a8653e

**Pull request merged**
