### PR TITLE
Use Incense And Lucky Egg

### PR DESCRIPTION
**Pull request by cawk**
Fixed issues and able to merge
will check every five minutes
and if one isnt active and you have one it will use it

### CODE REVIEW

**Comment by cawk** [comment]
Fixed it as the timer stopped at the end of the task (i really should read through the rest of the code) 
so made it check everytime it loots a pokestop but it wont waste them since it doesnt allow to be used if one is already active

**Comment by Ilses** [comment]
You forgot a few spaces (StatisticsAggregator.cs : 24, few places in Statistics.cs). 
Otherwise looking pretty good -- I'll start testing this.

**Comment by cawk** [comment]
Didnt want them commits with get level up rewards and revert how do i remove them from this pull request
i hate github sometimes

**Comment by cawk** [comment]
Why was this closed?

**Comment by Ilses** [comment]
I imagine yamashi wants you to rebase your commit..?

**Pull request closed without merging**
