### PR TITLE
Recycle, Evolve, Lucky Egg Logic and Settings

### PR DESCRIPTION
**Pull request by orangesuave**
Combined several other pull requests into this to merge with master better. 

Have added several settings to allow for better control of evolution/recycle/lucky egg logic.

Feel free to critique!

### CODE REVIEW

**Comment by orangesuave** [comment]
Tested and working with latest master build. Please provide feedback on results.

**Comment by mich3lam** [comment]
It's using STRINGS instead of INT for many settings in UserSettings.settings and few others

**Comment by orangesuave** [comment]
Updated. Please check.

**Comment by GDlike** [comment]
Its working fine for me, cause ure merging pulls requests, and working on giving more config power, could you add something like Keep**Max**DuplicatePokemon??

**Comment by Liliexx** [comment]
its not working on master branch

**Comment by orangesuave** [comment]
@Liliexx Can you please be more specific? What's not working for you?

**Comment by dbfy** [comment]
@orangesuave I can confirm it's not working, looking to see why, afik first off your 

> var duplicatePokemons =
                await
                    _inventory.GetDuplicatePokemonToTransfer(_clientSettings.KeepPokemonsThatCanEvolve,
                        _clientSettings.PrioritizeIVOverCP, _clientSettings.PokemonsNotToTransfer);

            BaseStats baseStats = PokemonInfo.GetBaseStats(duplicatePokemon.PokemonId);
                var max_cp = PokemonInfo.CalculateMaxCPMultiplier(duplicatePokemon);
                var min_cp = PokemonInfo.CalculateMinCPMultiplier(duplicatePokemon);
                var cur_cp = PokemonInfo.CalculateCPMultiplier(duplicatePokemon);

Is Erronous, due to the fact the `s` is there. I'll have to relook over all your commits.

**Comment by dbfy** [comment]
Figured it out.
`foreach (var duplicatePokemon in duplicatePokemons)` is missing before 
`BaseStats baseStats = PokemonInfo.GetBaseStats(duplicatePokemon.PokemonId);`

**Comment by yamashi** [comment]
Master is deprecated.

**Comment by orangesuave** [comment]
private async Task TransferDuplicatePokemon()
        {
            var duplicatePokemons =
                await
                    _inventory.GetDuplicatePokemonToTransfer(_clientSettings.KeepPokemonsThatCanEvolve,
                        _clientSettings.PrioritizeIVOverCP, _clientSettings.PokemonsNotToTransfer);
            
            foreach (var duplicatePokemon in duplicatePokemons)
            {
                var bestPokemonOfTypeIV = await _inventory.GetHighestPokemonOfTypeByIv(duplicatePokemon);
                var bestPokemonOfTypeCp = await _inventory.GetHighestPokemonOfTypeByCp(duplicatePokemon);

                BaseStats baseStats = PokemonInfo.GetBaseStats(duplicatePokemon.PokemonId);
                var max_cp = PokemonInfo.CalculateMaxCPMultiplier(duplicatePokemon);
                var min_cp = PokemonInfo.CalculateMinCPMultiplier(duplicatePokemon);
                var cur_cp = PokemonInfo.CalculateCPMultiplier(duplicatePokemon);

                var maxCPPercent = ((cur_cp - min_cp) / (max_cp - min_cp)) * 100.0;

                if (((duplicatePokemon.CalculateIV() >= _clientSettings.KeepMinIVPercentage) && (duplicatePokemon.Cp >= _clientSettings.KeepMinCP)) 
                      || (maxCPPercent >= _clientSettings.MaxCpPercent) && duplicatePokemon != bestPokemonOfTypeIV && duplicatePokemon != bestPokemonOfTypeCp )//add a keep max duplicate pokemon check.
                    continue;

                await _client.TransferPokemon(duplicatePokemon.Id);
                _inventory.DeletePokemonFromInvById(duplicatePokemon.Id);
                _stats.IncreasePokemonsTransfered();
                _stats.UpdateConsoleTitle(_inventory);
                var bestPokemonOfTypeAfter = _client.Settings.PrioritizeIVOverCP
                    ? await _inventory.GetHighestPokemonOfTypeByIv(duplicatePokemon)
                    : await _inventory.GetHighestPokemonOfTypeByCp(duplicatePokemon);
                Logger.Write(
                    $"{duplicatePokemon.PokemonId} with {duplicatePokemon.Cp} ({PokemonInfo.CalculatePokemonPerfection(duplicatePokemon).ToString("0.00")} % perfect) CP (Best: {bestPokemonOfTypeAfter.Cp} | ({PokemonInfo.CalculatePokemonPerfection(bestPokemonOfTypeAfter).ToString("0.00")} % perfect))",
                    LogLevel.Transfer);
                await Task.Delay(500);
            }
        }

**Comment by orangesuave** [comment]
This is the one. Finally those pesky Pinsirs and Magmars are gone.

**Comment by Liliexx** [comment]
i get an error cant run it , it says concel.exe missing something like that

**Comment by orangesuave** [comment]
You have to set Console as Startup Project. @Liliexx

**Comment by GDlike** [comment]
Why they closed every pull request? will not implement this? Is nice lol.

**Comment by Liliexx** [comment]
i did @orangesuave  but it keep saying i'm missing 2 files one is logic.dll and one for the console.exe

**Comment by Liliexx** [comment]
@orangesuave can you please give me a link for you're fork working?  its better than the dev branch

**Comment by yamashi** [comment]
We closed because we broke compatibility with master, if @orangesuave implements it for the new version of the bot we will merge it

**Comment by orangesuave** [comment]
What broke? I have this running with the master repo from today with no issues. My Fork says no commits behind.

**Comment by orangesuave** [comment]
I did have another idea, but I need some help: Any thoughts to fill in the blanks?:


//Needs actual Code here. List should be of unique PokemonId from list of PokemonID strings
new list pokemonidgroups

//This logic needs to be built out
var pokemonidgroup = PokemonNameString; 
 

//
for each (pokemonidgroup in list of pokemonidgroups)

	var bestPokemonOfTypeByIV = await _inventory.GetHighestPokemonOfTypeByIv():

	var bestPokemonOfTypeByCP = await _inventory.GetHighestPokemonOFTypeByCp();

	Logger.Write(
        	$"{pokemon.PokemonId} | CP: {encounter.WildPokemon?.PokemonData.Cp} | ({PokemonInfo.CalculatePokemonPerfection(encounter.WildPokemon?.PokemonData).ToString("0.00")} % perfect) CP (Best IV: {bestPokemonOfTypeAfterIV.Cp} | ({PokemonInfo.CalculatePokemonPerfection(bestPokemonOfTypeAfterIV).ToString("0.00")} % perfect))",LogLevel.Caught);
         Logger.Write(
		$"{pokemon.PokemonId} | (Best CP: {bestPokemonOfTypeAfterCp.Cp} | ({PokemonInfo.CalculatePokemonPerfection(bestPokemonOfTypeAfterCp).ToString("0.00")} % perfect))",LogLevel.Caught);

await Task.Delay(500);

**Comment by yamashi** [comment]
"This branch is 15 commits ahead, 64 commits behind NecronomiconCoding:master. "

**Comment by orangesuave** [comment]
@Liliexx and @yamashi When I merge it with the new base I'll let you know. Probably will work on it this weekend. I wanted to verify all the iterative updates since this initial commit were working properly. I've had it running now for about 12 hours with no errors relating to evolution, transferring pokemon, or item capacity.

**Pull request closed without merging**
