### PR TITLE
Added new translation strings and russian translation file

### PR DESCRIPTION
**Pull request by panthernet**
Op!

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
remove csproj include

**Comment by NecronomiconCoding** [comment]
btw u look like putin in young :laughing:

**Comment by panthernet** [comment]
Why remove them?  This way they can be put into output folder automatically. Or do you have another logic in mind?

**Comment by panthernet** [comment]
Removed it as you asked for, but still don't get it :)

**Comment by NecronomiconCoding** [comment]
@panthernet because i am going to add them to the csproj now

**Comment by panthernet** [comment]
kk, thanks

**Pull request merged**
