### PR TITLE
EvolveAllPkm Management - Evolve all above certain IV value

### PR DESCRIPTION
**Pull request by skupfer**
Evolve all pokemon can be true and/or evolveallaboveiv
there evolveaboveivvalue comes into play ...

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
was this tested?

**Comment by skupfer** [comment]
Several times. Proceeded with login and stuff. But it's always better if someone tests something, too

**Comment by solenrus** [comment]
pretty cool feature

**Comment by NecronomiconCoding** [comment]
2 errors you gotta fix m8

**Comment by skupfer** [comment]
fixed one in RocketAPI/ISettings.cs but you where too fast

**Pull request merged**
