### PR TITLE
Sniper with automated pokelocation feed

### PR DESCRIPTION
**Pull request by 5andr0**
See for yourself: [Image](https://dl.dropboxusercontent.com/u/28069358/wow.jpg)

The client connects to an open source server made by @Ilses and me:
https://github.com/5andr0/PogoLocationFeeder/tree/master/PogoLocationFeeder

Right now it is crawling new pokemon locations from the discord channel #sniping 
and sending them via json to the client. This can be improved to be a pokevision scraper etc

```
  "SnipeAtPokestops": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,
  "UseTransferIVForSnipe": false,
  "MinDelayBetweenSnipes": 20000,
```

There's a major bug in FarmPokestopsGPXTask.cs
where `while (pokestopList.Any())` is never true because pokestops are already @ cooldown because of UseNearbyPokestopsTask. So all the calls in the loop are never executed (or 1 in 100). That's why i had to move the SnipePokemonTask call out which is then called more often. So i added the MinDelayBetweenSnipes.

More info on our wiki page: [PogoLocationFeeder Wiki](https://github.com/5andr0/PogoLocationFeeder/wiki)

Quick tutorial:
- connect your discord account to the [NecroBot server](https://discord.gg/VsVrjgr)
- start the PogoLocationFeeder to generate the config.json and enter your discord logins
- start it again and run your necrobots. now wait until someone posts into #sniping 

Can we find somebody to host the feeder so everybody can connect via ip+port?

Please help me to improve the feeder project. Todo: location database with continuous pokevision scraping. Or anything that helps to get locations.

Make sure you filled your PokemonToSnipe array:
```
"Pokemon": [
      "Dratini",
      "Magikarp",
      "Kangaskhan",
      "Eevee",
      "Charmander",
      "Snorlax",
      "Chansey",
      "Exeggutor",
      "Aerodactyl",
      "Vaporeon",
      "MrMime",
      "Magmar",
      "Dragonite",
      "Raichu",
      "Venusaur",
      "Slowbro",
      "Porygon",
      "Farfetchd",
      "Poliwrath",
      "Dragonair",
      "Charizard",
      "Blastoise",
      "Muk",
      "Gyarados",
      "Arcanine",
      "Machamp"
    ]
```

### CODE REVIEW

**Comment by mich3lam** [comment]
Wow, this is epic!

**Comment by Ilses** [comment]
Before anyone asks, the bot will not be made public until one of the discord admins restricts the permissions to read-only on the #sniper channel. At that point, there will likely be another PR to change the default settings.

**Comment by carlanivans** [comment]
how do i add this to my bot...sorry noob here

**Comment by mich3lam** [comment]
@Ilses i am giving this a run now! :D

**Comment by carlanivans** [comment]
@mich3lamok thanks will do....btw been using this bot for days now and its amazing

**Comment by mich3lam** [comment]
@carlanivans i am a lil bit confused about the:
{
  "ServerId": 0,
  "ServerChannel": "",
  "DiscordToken": "",
  "Port": 0
}
how do i retrieve those

**Comment by Ilses** [comment]
@mich3lam Once again, that's the part we haven't made public. Our bot has too many permissions on the server, so waiting on an admin to cut those or it will get abused.

**Comment by mich3lam** [comment]
@Ilses Oh ahaha so i cannot really test it for now :<

**Comment by carlanivans** [comment]
@mich3lam @Ilses yeah making that public would make it go viral.....lets just wait for the combined release...right now my bot stops after every 30 mins and sniping shows no pokemon so im kinda sitting ducks here XD

**Comment by mich3lam** [comment]
@carlanivans this actually stops the sniping from the setting.cs right ? these don't work anymore, i mean the ones in the bottom with coordinates

**Comment by carlanivans** [comment]
@mich3lam ahhhh ok thanks maybe those coordinates are dry now......but still no solution for my bot not working after 30 mins

**Comment by 5andr0** [comment]
I just added discord user login ability: https://github.com/5andr0/PogoLocationFeeder/commit/3724afa592fc8696a5d4a029c57281c3007571be

**Comment by mich3lam** [comment]
so with this we can actually use it now?

**Comment by carlanivans** [comment]
@mich3lam i just manually go there and farm and use quick spin to get unbanned XD

**Comment by 5andr0** [comment]
yes @mich3lam it's ready to use, just pull my sniper branch from https://github.com/5andr0/NecroBot.git

**Comment by mich3lam** [comment]
@5andr0 ye i have already compiled everything localy..
http://i.imgur.com/lkmxMko.png
too bad the bot isnt brining anythings to tets it xd

**Comment by carlanivans** [comment]
@5andr0 is there any way to add and compile without visual studio?

**Comment by 5andr0** [comment]
Use this server id: 206232715530338305 from [PokemonGo Rare Hunting](https://discord.gg/sTQBGpm) and channel high_iv_pokemon or rare_pokemon

**Comment by mich3lam** [comment]
@5andr0 i wanted to test it
made a random channel on my server
and this happens
http://i.imgur.com/RF9TOIc.png
why?

**Comment by mich3lam** [comment]
i mean, it reads but the bot doesn't do anything with it

**Comment by 5andr0** [comment]
pm me on discord please @mich3lam

**Comment by Marsinator** [comment]
maybe make him snipe only for pokemon with the best skill sets?
those can be found here: https://docs.google.com/spreadsheets/d/1I0Kt_QblThH2rf7vdZOC2L1Nuf7Y1xx68j_KYwfcpXc/htmlview?sle=true#

**Comment by carlanivans** [comment]
@5andr0 @mich3lam  sorry for posting again but why is bot not working after 30 mins?

**Comment by hungvinh** [comment]
Sounds cool, I'm now in the discord group. How do I go about setting it up? Should I leave coordinates in the config.json for necrobot or remove them completely and leave "SnipeAtPokestops" as True?

**Comment by hima-n** [comment]
How to use it, i cant down it!

**Comment by 5andr0** [comment]
@carlanivans that might be necrobot related, please seek for help in the discord help chats.
@hungvinh SnipeAtPokestops has to be True and you have to set your coords as usual where you don't get a softban.

**Comment by maxleveling** [comment]
I am sorry i need help, why i running 7 hour but didnt get any monster from sniping.
No single dratini or magicrap i get.

[13:13:02] [Sniper] Scanning for Snipeable Pokemon at 38,5568074864611,-121,238379478455...
[13:13:02] [Sniper] No Pokemon found to snipe!
[13:13:02] [Sniper] Scanning for Snipeable Pokemon at -33,859019,151,213098...
[13:13:03] [Sniper] No Pokemon found to snipe!
[13:13:03] [Sniper] Scanning for Snipeable Pokemon at 47,5014969,-122,0959568...
[13:13:03] [Sniper] No Pokemon found to snipe!
[13:13:03] [Sniper] Scanning for Snipeable Pokemon at 51,5025343,-0,2055027...
[13:13:04] [Sniper] No Pokemon found to snipe!

Maybe you can solve the problem, thk u before

**Comment by rcgary** [comment]
@maxleveling "38,5568074864611,-121,238379478455..." should be `.` not `,`

**Comment by Naprosnia** [comment]
Another thing that can be very cool, is to add support for reading the api from http://pokesnipers.com/.

**Comment by ricoxor** [comment]
@mich3lam How do you add the change on your NecroBot ? Manually ?

**Comment by hima-n** [comment]
http://puu.sh/qiure/2009fb0c8a.png @5andr0 

empty?

**Comment by hima-n** [comment]
@maxleveling same problem ..

**Comment by marksterxxx** [comment]
thanks to this i am farming snorlax fast.... you guys make sure to add the pokemon in your snipe list in config.

**Comment by ricoxor** [comment]
I merged your pull and I have this error : http://puu.sh/qivcV/f9d2691bf5.png

**Comment by hima-n** [comment]
@marksterxxx how u used it?

**Comment by Ghawken** [comment]
Hi
Great idea - PogoFeeder - working and running - see photo.
However complied your version - and gets sniper info from PogoFeeder - but doesn't seem to do anything with it?
Glenn
http://i66.tinypic.com/161jj43.png

**Comment by hima-n** [comment]
@Ghawken

How to do it? sir

**Comment by mich3lam** [comment]
@Ghawken ye how did u manege the fix it buddy ?

**Comment by LazerMouze** [comment]
Hi my NercroBot doesn't have the "SnipeLocationServer", "SnipeLocationServerPort" and "UseSnipeLocationServer" setting in the config.json. Do any of you know how to fix that?

**Comment by Ghawken** [comment]
all instructions in this thread - as above
until merged to main necrobot

build branch here:

https://github.com/5andr0/NecroBot/tree/sniper

**Comment by skupfer** [comment]
On Startup
```Unbehandelte Ausnahme: Newtonsoft.Json.JsonSerializationException: Error converting value "exeggcutor" to type 'POGOProtos.Enums.PokemonId'. Path 'PokemonToSnipe.Pokemon[27]', line 372, position 18. ---> System.ArgumentException: Der angeforderte Wert "exeggcutor" konnte nicht gefunden werden.
   bei System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   bei System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   bei System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   bei Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   bei Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei PoGo.NecroBot.CLI.GlobalSettings.Load(String path) in E:\Downloads\PokemonGo\5andro_Sniper\5andr0_NecroBot_Sniper\PoGo.NecroBot.Logic\Settings.cs:Zeile 294.
   bei PoGo.NecroBot.CLI.Program.Main(String[] args) in E:\Downloads\PokemonGo\5andro_Sniper\5andr0_NecroBot_Sniper\PoGo.NecroBot.CLI\Program.cs:Zeile 31.```

**Comment by UgaBugaBoo** [comment]
How do I add a new channel ?

**Comment by miraclesuki** [comment]
Sorry, the PogoLocationFeeder after build and can start and show properly (getting info from dicord). 
I've configured the config.json in necroBot, however everytime I start the bot, it automatically removed the following added snippets, what's the reason? thanks!
  "SnipeAtPokestops": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,
  "MinDelayBetweenSnipes": 20000,

**Comment by UgaBugaBoo** [comment]
@5andr0  It keeps scanning old coordinates which it already scanned and sipped

**Comment by LazerMouze** [comment]
I'm a complete github noob so can someone tell me what to do to get these settings to show up in my NercoBot config: "SnipeLocationServer", "SnipeLocationServerPort" and "UseSnipeLocationServer".

**Comment by LoloLaurentiu** [comment]
wow this is awesome can't wait for the merge

**Comment by rayn21dev** [comment]
Pulled this into my bot, works great! Now if only I didn't have to restart the bot every 30 seconds.

**Comment by Bogenschuetze** [comment]
"SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,
  "MinDelayBetweenSnipes": 5000,

**Comment by Ghawken** [comment]
@5andr0 Thanks - seems to keep old sniping locations forever - 15 minutes remove doesnt seem to occur.?

**Comment by jaskovic** [comment]
guys wehere i need to put this item in ; 
{
  "ServerChannels": [
    "sniping",
    "high_iv_pokemon",
    "rare_pokemon"
  ],
  "DiscordToken": "",
  "Port": 16969,
  "useToken": false,
  "DiscordUser": "discord_mail",
  "DiscordPassword": "discord_pwd"
}

??

**Comment by 5andr0** [comment]
@jaskovic PogoLocationFeeder -> config.json

**Comment by miraclesuki** [comment]
Hi,

I was compiled the new branch of incasesensitive, no more sniper info from the console.
Any Idea? Thanks!!

http://i65.tinypic.com/34zj2nc.jpg

**Comment by 5andr0** [comment]
@miraclesuki no idea, pm me on discord

**Comment by l3uddz** [comment]
This works really well. Good job. Hope it gets merged.

**Comment by nenko91** [comment]
@5andr0 where to find you in discord? ^^

**Comment by Ghawken** [comment]
Hi. thanks for the work on this

why does it scan locations without a selected pokemon?

(eg. Missingto not included in snipe pokemon list, but Bot snipes locations with Missingto - doesnt find any - but shouldn't it not save the location data for unselected pokemon id?)

**Comment by Lastnet0709** [comment]
help :(

http://pastebin.com/b1t9Sbdn config.json necrobot

**Comment by rankin1981** [comment]
When ever i add 

  "SnipeAtPokestops": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,
  "UseTransferIVForSnipe": false,
  "MinDelayBetweenSnipes": 20000,

To necro bot config.json
and start Necro bot those lines get removed

**Comment by nenko91** [comment]
I've got NecroBot working and PogoLocationFeeder working, but can't connect them. My necrobot config file doesn't update with the server options. I've read that I have to "build branch here:

https://github.com/5andr0/NecroBot/tree/sniper". Could someone explain how to do it or give some tips?

**Comment by hima-n** [comment]
**CAN ANYONE WRITE A TUTS FOR IT?**

**Comment by Ilses** [comment]
See our wiki page.

**Comment by skupfer** [comment]
I used the fork from 5andr0 before but it doesn't has the 30min fix included... Since I am lazy today I decided to give NecroBot a try again (still using prefork-modified^^).

With 5andr0s fork the Sniperfunction was working perfectly fine. After this got merged in I pulled the latest commit be2f597 and it rarely snipes even if the PogoLocationFeeder is getting massively filled ... 

Using the same settings I would argue its an setting-related. Haven't found out yet what the issue is :-/ but I guess it could be related to changes after this merge to sniper related tasks...

**Comment by Ilses** [comment]
@nenko91 You need to be on the latest version. They should automagically be added as config options the next time you run NecroBot.

@skupfer GTX logic doesn't give sniping enough time right now. You can modify it, or use non-GPX.

**Comment by nenko91** [comment]
@Ilses I am on the latest version

**Comment by skupfer** [comment]
@Ilses Already on non-GPX here

**Comment by hungvinh** [comment]
How exactly do I compile necrobot to use with this?

**Comment by hima-n** [comment]
waiting for @hungvinh

**Comment by nenko91** [comment]
When I download the source code and open the solution it doesn't load PokemonGo.RocketAPI and it says it's unavailable and I can't find it in the folders either. How do I fix that? Is it my VS?
The release version works fine, but can't set it to work with PogoLocationFeeder

**Comment by mvegter197** [comment]
@nenko91 You need to download the API separately and put it in the FeroxRev folder.

**Comment by nenko91** [comment]
@mvegter197 Cheers, man! Been headbanging since yesterday over that.

**Pull request merged**
