### PR TITLE
Additional information egg hatched event

### PR DESCRIPTION
**Pull request by RoseFlunder**
Added additional information to egg hatched event (level, cp, iv) and changed the logging for this event accordingly.

Moreover the event and the egg status update event will use the EGG log level and is thus printed in dark yellow.

### CODE REVIEW

**Comment by ifbatmanwasreal** [comment]
That's awesome. I was just thinking a few minutes ago what happens after the egg hatches. I know I've hatched a lot, no idea what came from them though.

**Comment by Sulvyr** [comment]
hi! Is any way to set a priority of eggs in incubator? Like  10km high priority then 5km and last 2km.

**Comment by mich3lam** [comment]
Compiles great! thank you! :)

**Comment by RoseFlunder** [comment]
@ifbatmanwasreal There is already a logic implemented which prefers "long" eggs for limited incubators:
`var unusedEggs = (await session.Inventory.GetEggs())
                .Where(x => string.IsNullOrEmpty(x.EggIncubatorId))
                .OrderBy(x => x.EggKmWalkedTarget - x.EggKmWalkedStart)
                .ToList();`
...
`// Unlimited incubators prefer short eggs, limited incubators prefer long eggs`
`var egg = incubator.ItemId == ItemId.ItemIncubatorBasicUnlimited
                        ? unusedEggs.FirstOrDefault()
                        : unusedEggs.LastOrDefault();`

**Comment by ifbatmanwasreal** [comment]
@RoseFlunder That's cool. I'm not too worried about which incubators are used. I'm wondering what Pokemon I get when the egg hatches.

**Comment by RoseFlunder** [comment]
I merged the latest changes to resolve all conflicts

**Pull request merged**
