### PR TITLE
fixed gpx bug, add new gpx functionality for loop numbers and data ou…

### PR DESCRIPTION
**Pull request by lilpug**
this fixes the gpx bug for constant loop over on segment 1 track points, i have also tidy up the code and implemented the ability to have extra configurations around gpx including loops numbers, data outputs etc.

### CODE REVIEW

**Comment by Lejuke** [comment]
Hi, i am having some problems with the bot in the last hours, here is an example (I get sofbanned because of the distance, i cant see the name of the pokestops, just the distance) I have tired with more ccounts and it is the same, my coords are the Necrobot defaulf.


example

**Comment by lilpug** [comment]
is this to do with my pull request code changes or in general?

**Comment by luigidanield2** [comment]
anche io ho questo problema!mi dice pokestop non trovati nella zona.distanza massima troppo corta?prima funzionava.... cosa puo essere?????

**Comment by NecronomiconCoding** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
