### PR TITLE
Revert to old README.md

### PR DESCRIPTION
**Pull request by nightmare911**

### CODE REVIEW

**Comment by cpasmoi** [comment]
retarded ?

**Comment by MEGALELZ** [comment]
It seems like they got dooped to be honest. One does not simply remove an entire OPEN SOURCE project.

**Comment by bredmich** [comment]
@NecronomiconCoding what happened ?

**Comment by bredmich** [comment]
New project: https://github.com/DurtyFree/PokeMobBot

**Comment by hilycker** [comment]
@bredmich that has still to be proven, I'd like to hear something from @NecronomiconCoding first

**Comment by bredmich** [comment]
@hilycker yeah me too. I don´t think he´s still sleeping ...

**Comment by hilycker** [comment]
I heard about drama between NecronomiconCoding and others, and I heard that NecronomiconCoding's github account was hacked and project hijacked.

Both rumors until proven.

Still, things went down in a weird way, so..

**Comment by bredmich** [comment]
That´s a big problem of open source projects with many developers that have never met eachother.

**Comment by Sylencer90** [comment]
ugh i felt something like that coming, open source always gets leeched off for profit.

**Comment by bredmich** [comment]
No Statement ?

**Comment by NecronomiconCoding** [comment]
its coming.

**Pull request closed without merging**
