### PR TITLE
Added Navigation via Open Street Maps for a more realistic movement between Pokestops

### PR DESCRIPTION
**Pull request by NecktiedHummingbird**
image

### CODE REVIEW

**Comment by Oolaruu** [comment]
Wow this is really cool, would it be possible to skip few "irrealistic" routes ?
http://prntscr.com/c3h11w

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by Kotentopf1337** [comment]
Fixxed conflicts

**Comment by Kotentopf1337** [comment]
Not working with latest changes. I'm on it.

**Comment by Kotentopf1337** [comment]
I hate cultures.. ^^

**Comment by Andrerm124** [comment]
I really like this idea! However wouldn't it be better to use `Thread.CurrentThread.CurrentCulture;` instead of creating a new one?

**Comment by NecronomiconCoding** [comment]
What happens if there are no Streets near a pokestop?

**Comment by Simpuhl** [comment]
What happens if at a park/beach/pier/open area with pokestops

**Comment by djdookie** [comment]
Nice idea, but i think better gpx-files should also work!
You don't walk streets all the time.

**Comment by lorilith** [comment]
looks good. Problem is that it walks around buildings past pokestops to grab the one it is aiming for. slows progression WAY down.  Pathing is good, but if the "next pokestop distance" algorithm doesnt account for it, it fails miserably.

**Comment by uz19ibyd** [comment]
haha :D you passed by my house

**Comment by Kotentopf1337** [comment]
Startet at a playground in a forest. Directly navigated to the stops at playground without OSM
image

**Comment by somani6** [comment]
i think this is phantastic, but in my case it made a weird decision what pokestop to go to first.
And the 100m limit does not allow "real" rutes in a more urban area

image

It got straight to a fairly remote pokestop wihtout touching any of the stops on the route there.

**Comment by DBa2016** [comment]
Please change "UseOsmNavigat**ing**" to "UseOSMNavigat**ion**"

**Comment by TheMaskedMonkey** [comment]
This looks dope! Can't wait for it to be merged and released! :)

**Comment by xidus90** [comment]
Can't wait too <3

**Comment by nilsbrychzy** [comment]
Great feature against Niantics try to ban us

**Comment by estebanstateside** [comment]
This feature looks freaking awesome, can't wait for it to be merged and deployed!

**Comment by Naprosnia** [comment]
Pls add option to disable this feature, like "DisableFollowRoutes: false". Beacause it reduce bot speed for farming (point A to point B in straight line is always faster than follow routes). And no one was banned by walking in a straight line.

**Comment by nilsbrychzy** [comment]
There's already something Mike this!

```bool UseOsmNavigation { get; }```

**Comment by Kotentopf1337** [comment]
And by default it is disabled
`[DefaultValue(false)]
public bool UseOsmNavigation;`

**Comment by Naprosnia** [comment]
Ok ;)

**Comment by xidus90** [comment]
@Kotentopf1337 "This branch has conflicts that must be resolved" :(

**Comment by Kotentopf1337** [comment]
@xidus90 Merged

**Comment by xidus90** [comment]
@Kotentopf1337 Next Time : "This branch has conflicts that must be resolved" :(

Are you from Germany?

**Comment by deduijk** [comment]
Awesome. If possible i think it should be 2 options:
1 for the street like walking
and 1 for vector variances. (see 5128)
The vector variances will not influence the bot speed, but will still make it look a lot more like a human walking. (you could even set the perpendicular movement so high the bot would look drunk xD).

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by Kotentopf1337** [comment]
Updated

**Comment by somani6** [comment]
Hm there are some differnces between the API and the website. Navigation from 47.374458,8.541778 to 47.376008,8.535421 looks fine on the website. 0.59km, 34 directions

Using the API (http://www.yournavigation.org/api/1.0/gosmore.php?format=kml&flat=47.374458&flon=8.541778&tlat=47.376008&tlon=8.535421&v=foot)
I get only 3 waypoints for no obvious reason.

it's NOT an implementation Error, it's wrong on YOURs side.

**Comment by SaubereSacheLP** [comment]
How long will it need to add this to the master branch?

**Comment by FabryB** [comment]
@Kotentopf1337 I have merged your changes in my fork and added some changes.
Please have a look: https://github.com/FabryB/NecroBot/tree/open-street-map

**Pull request closed without merging**
