### PR TITLE
Added feature to reset coords based on distance and time last run

### PR DESCRIPTION
**Pull request by CTDragon**
Added feature to reset coords based on distance and time last run

Also fixed bug with log causing crash in master branch

### CODE REVIEW

**Comment by CTDragon** [comment]
Merged with latest master and reviewed Logger merge

**Comment by NecronomiconCoding** [comment]
conflicts :)

**Comment by CTDragon** [comment]
Resolved again

**Comment by NecronomiconCoding** [comment]
So what exactly has been added?

**Comment by CTDragon** [comment]
When the program is first run, if the user could have traveled realistically back to the default location from the last known location, it deletes the coords.ini file so the logic will start from the default location.

**Comment by CTDragon** [comment]
The code essentially looks and says if (distanceBetweenDefaultAndLastKnownLocation/timeCoordsLastUpdated) < 80kmph), start at the default location, otherwise continue from last known location and continue as normal.

**Comment by CTDragon** [comment]
I have tested it with the latest merges and it works

**Comment by CTDragon** [comment]
The point is, I (and someone who submitted an issue) like to start from the default location because there are several stops right there. If I haven't run it in a while, I want to start from that default point where there are several stops, not somewhere else.

**Comment by CTDragon** [comment]
image

I do want it to venture out from there though and not set too small of a max travel distance because all that area has is pidgey and ratatta. lol.

**Comment by solenrus** [comment]
seems like a great feature to me

**Comment by OverlordQ** [comment]
This is the stupidest 'realistic' idea ever.

**Comment by CTDragon** [comment]
It's not a realistic feature, it's a start over without deleting the coords file feature...

**Pull request merged**
