### PR TITLE
farm pokemon

### PR DESCRIPTION
**Pull request by lnkakalink**
make points selection function for farm Pokemon
. Statistics also do in places where there is information about how the site around the points and so on.
just lay out their coordinates to farm here

### CODE REVIEW

**Comment by lnkakalink** [comment]
"DefaultLatitude": -33.8731667,
  "DefaultLongitude": 151.2082071,

**Comment by Fenixxia** [comment]
Dear developers. You have done a lot. But still not entered one of the main filters to pokemon! Check for a match "Type of pokemon" = "attack type pokemon". This correspondence is called STAB. Attack pokemon gets a bonus of 1.25. Pokemon without STAB loses to pokemon with STAB at the same LV, CP, and IV of about 25-30%. 
Now collect all the pokemon based on the priority IV, but why is it needed without STAB?
Because the type of attack the pokemon can change during the evolution of such compliance testing need to take place for 2 and 3 levels of evolution. 
With great hope for the early entry of such functions.

**Comment by Ilses** [comment]
@Fenixxia This is a pull request, not a feature request. Save your entry for the return of the issue tracker, please.

**Comment by Fenixxia** [comment]
I have no way to make a request to add new features through Github

**Comment by Ilses** [comment]
You're hijacking a PR. PM a dev, or hold off on the request for now.

**Pull request closed without merging**
