### PR TITLE
Error when running the Bot?

### PR DESCRIPTION
**Pull request by exoticminge**
Unhandled Exception: Newtonsoft.Json.JsonReaderException: After parsing a value
an unexpected character was encountered: ". Path 'PokemonsNotToTransfer[14]', li
ne 156, position 4.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(Jso
nReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IL
ist list, JsonReader reader, JsonArrayContract contract, JsonProperty containerP
roperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(Json
Reader reader, Type objectType, JsonContract contract, JsonProperty member, Obje
ct existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValu
e(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract
containerContract, JsonProperty containerProperty, JsonReader reader, Object tar
get)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(
Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty m
ember, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Js
onReader reader, Type objectType, JsonContract contract, JsonProperty member, Js
onContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
 objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, Jso
nSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSeriali
zerSettings settings)
   at PoGo.NecroBot.CLI.GlobalSettings.Load(String path) in C:\Users\TYLaptop\De
sktop\BOT\NecroBot-master\PoGo.NecroBot.Logic\Settings.cs:line 264
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\TYLaptop\Desktop
\BOT\NecroBot-master\PoGo.NecroBot.CLI\Program.cs:line 31
Press any key to continue . . .

### CODE REVIEW

**Comment by ManStache** [comment]
Im getting a similar error, but for the auth.json file instead of config.json. Bot won't run at all since the update for me.

**Comment by Gunz1** [comment]
No idea why they made it like this, but you have to add "" around password and username. fixed for me.

**Comment by marisancans** [comment]
Same, update broke it

**Comment by NecronomiconCoding** [comment]
use a comma and read the wiki.

**Comment by marisancans** [comment]
You should add it as a comment in that file

**Comment by NecronomiconCoding** [comment]
you cant add comments,also you should know basic json to run this bot

**Comment by mochdev** [comment]
please change manual key pressing to continue the bot to auto continue like time count down

**Comment by exoticminge** [comment]
Still unsure how to fix :(

**Pull request closed without merging**
