### PR TITLE
Prompt for credentials if they are not already present in config file.

### PR DESCRIPTION
**Pull request by nekcih**

### CODE REVIEW

**Comment by h3300420** [comment]
I am sorry to you, I do not know  how to ask a questions.    
  How to cancel "press any key to " when it is  restart.

**Comment by NecronomiconCoding** [comment]
Sorry but this was declined

**Comment by lko0o** [comment]
@h3300420 just setting "StartupWelcomeDelay" to false,

**Comment by mich3lam** [comment]
@h3300420 you say he cant ask question but you cannot read. thats not even what he asked

**Comment by nekcih** [comment]
I'm not sure what you mean.  Can you try to translate with google?
https://translate.google.com/

This change only asks the user for their user and password if they were not already in the auth.json. Pressing enter/return completes the input as you can see here...

https://github.com/NecronomiconCoding/NecroBot/pull/1467/files#diff-39f98193027b1e3efd042f220bf2646dR645

**Comment by nekcih** [comment]
Uh...  ok.

**Pull request closed without merging**
