### PR TITLE
Custom pokeball on capture

### PR DESCRIPTION
**Pull request by AlessioDP**
First code pull request. Tell me if i made some mistakes thanks :)

### CODE REVIEW

**Comment by mich3lam** [comment]
sessionLogicSettings does not exist on the current context

**Comment by AlessioDP** [comment]
Updated, thanks @mich3lam

**Comment by NecronomiconCoding** [comment]
This branch has conflicts that must be resolved

**Comment by AlessioDP** [comment]
@NecronomiconCoding conflicts with?

**Pull request closed without merging**
