### PR TITLE
Add of a pokemap showing user position and place where user catched pokemon

### PR DESCRIPTION
**Pull request by adriendomoison**
Add of a Form Window + GreatMap
Use GoogleMap
Get pokemon catch position and user position

### CODE REVIEW

**Comment by mich3lam** [comment]
can you upload a screenshot of how it looks?

**Comment by adriendomoison** [comment]
pokemap
pokemap3

**Comment by yamashi** [comment]
Please contribute to the official UI, we can't merge that in
https://github.com/yamashi/NecroUI

**Comment by ScaryEnderman** [comment]
awesome

**Pull request closed without merging**
