### PR TITLE
Pokemon are evolved before being transferred, and transfer less often

### PR DESCRIPTION
**Pull request by Daylend**
Items/pokemon will only be evolved/transferred once every 5 stops.

Planning on adding a config option and a check to see if the bag is full at a later time.

### CODE REVIEW

**Comment by solenrus** [comment]
good shit, I was using the 
```
if (_clientSettings.EvolveAllPokemonWithEnoughCandy)
                    await EvolveAllPokemonWithEnoughCandy(_clientSettings.PokemonsToEvolve);
``` pretty much everytime, but it's kinda individual

**Comment by cvax** [comment]
Using evolve every 5 stops basically means you expend all your candies evolving something that might not be worth evolving if you haven't caught something good yet. Not sure it is desirable to waste candies like this.

**Comment by Antidote78** [comment]
You could set how many pokestop you want to wait before evolving in the settings

**Comment by Daylend** [comment]
@Antidote78 "Planning on adding a config option". So yeah, if this gets accepted, I will go further with this.

**Pull request merged**
