### PR TITLE
Set snipe timeout to avoid waste of time.

### PR DESCRIPTION
**Pull request by nongdun**
Set snipe timeout to avoid waste of time, especially when network is unstable.

### CODE REVIEW

**Comment by mochdev** [comment]
help me
how to disable snipe feature ?

**Comment by Tsuki** [comment]
It seem that snipe will hang when searching pokemon

**Comment by carlanivans** [comment]
@Tsuki my bot isnt working after 30 mins is there a solution to this?

**Comment by dody19852002** [comment]
maybe adding an option to change pokestop number to visit before autosniping at config file will be great. sometime sniping takes a lot of pokeball, need more than 5 pokestops to gather the ball.

**Comment by can99** [comment]
1. the bot stopped working after a while when sniping is enabled
2. need to stop sniping loop or break from the loop when pokeball is empty
if it could stop sniping after pokeball counter reach certain number it would be better
3. need to stop the loop or break from the loop and start do transfer when pokemon inventory is full and transfer duplicate is on

**Comment by Tsuki** [comment]
@carlanivans yes you need yo disabled in config

**Comment by gbdematos** [comment]
Can someone explain to me what exactly sniping is?
I set some coordinates to Pokémon locations, put them on the list, but no Pokémon is caught, ever. 
It stayed all night like this. What am I missing?

**Comment by spinnerwestside** [comment]
No Pokeballs - We missed a Charmander with CP 

keep getting this error

**Comment by Lastnet0709** [comment]
how to set server
"SnipeLocationServer": "???",
"SnipeLocationServerPort": "???"

**Comment by urkox89** [comment]
[img]http://puu.sh/qiF4e/4c28b8783a.png[/img] or http://puu.sh/qiF4e/4c28b8783a.png

Necrobot v0.3.3 :/

**Pull request merged**
