### PR TITLE
changing location makes catches become catchflee

### PR DESCRIPTION
**Pull request by michaelho516**
every time i change my latitude and longitude, the first few pokemons bot detects must be catchflee, is it a bug?

### CODE REVIEW

**Comment by ogAgliff** [comment]
its a softban from you teleporting, i do believe.

**Comment by michaelho516** [comment]
oh really? so if i saw any special pokemon, there is no way for me to catch them by teleporting to that spot? is there any way to figure it out?

**Comment by brama23** [comment]
wait 2 hours to change the location of the previous location if you do not want exposed softban

**Comment by brama23** [comment]
I just want to know the beginner course, if you want to edit PoGo.NecroBot.CLI folder , the folder NecroBot - 0.3.3 , NecroBot - 0.3.3.tar is attached where ? in a release or a folder where ?
because all this time I was wearing only release folder only.
could you please explain where the folder ?

thanks for your answer :)

**Comment by IamLupo** [comment]
2016-07-30 8:36 GMT+02:00 brama23 <notifications@github.com>:

**Comment by massi93** [comment]
he
Guys, how do you solve this problem? I can't figure it out

**Comment by jerryhii** [comment]
Try to increase your MaxTravelDistanceInMeters. See if that helps

**Comment by massi93** [comment]
ok i will try. Its weird because i didin't have this problem until now. Thanks

**Comment by rezarizky90** [comment]
Anyone why my sniper always shows not found pokemon?

**Comment by ChenGaoYuan** [comment]
@rezarizky90 That's righr

**Comment by IamLupo** [comment]
this happends because nianic has made a patch and changed a lot of pokemon
positions:

More info here:
https://www.reddit.com/r/TheSilphRoad/comments/4v78mw/psa_nests_have_changed/?compact=false

2016-07-30 9:51 GMT+02:00 rezarizky90 <notifications@github.com>:

**Comment by rezarizky90** [comment]
Anyone can give a location for sniping?

**Comment by Xomux** [comment]
Is it normal that sniping mode is not working? I turned on all settings in the config file and i didn't see anything in the cmd console.

**Comment by lotusJDM** [comment]
Anyone wanna help me with my problems lool?
image

**Comment by sedk** [comment]
I think I faced it already...
You're trying to start at longitude -220 and that's out of range. The yellow log entry is quite explicit. Check your config.json : 
  "DefaultLatitude": xxxx
  "DefaultLongitude": yyyy

**Comment by lotusJDM** [comment]
@sedk Thanks a bunch.

**Comment by Ilses** [comment]
This isn't a PR. Close, please.

**Pull request closed without merging**
