### PR TITLE
[add] Never spawn at the same position. Niantic might detect that!

### PR DESCRIPTION
**Pull request by Floppixx**
Dont know if they do it. But better safe than sorry!

### CODE REVIEW

**Comment by Jackman1000** [comment]
Yeah, suddenly, im not spawning in the same location as the one in my .ini

**Comment by stainx** [comment]
Would it be possible to cache the bots last known position for the next time it loads? With an manual override option for new locations.

**Comment by mich3lam** [comment]
this commit ruins the bot, it will always start somewhere and then it';ll need to walk back..

**Comment by Floppixx** [comment]
Oh yes. Increse the offset.

**Comment by Zuxser** [comment]
Nice idea, bu on equator 0,2 deg in each direction might be up to 30 km from origin place (max on equator).
untitled

**Comment by Floppixx** [comment]
Yes. 0,2 is to much. Never got that on my tests. Should be max 0,05

**Pull request merged**
