### PR TITLE
Sniper NO LONGER Sniping Anything. No Pokemon found.

### PR DESCRIPTION
**Pull request by ShallowHacker**
I have over 20 coords. It was working fine and now it wont snipe anything. Still catches normal fine.
Can I get help or did Niantic catch on or something?

### CODE REVIEW

**Comment by 089flo** [comment]
looks like, i have also since 5 Minutes also nothing to snipe :-(

**Comment by tatgod91** [comment]
same here im barely even catching pokemon

**Comment by ShallowHacker** [comment]
Sniper Broke. :( Is there a possible fix or are we burnt now? :-1:

**Comment by Klever04** [comment]
It seems like the nests have recently changed link. 
https://www.reddit.com/r/TheSilphRoad/comments/4v78mw/psa_nests_have_changed/

**Comment by ShallowHacker** [comment]
I'm Sniping only Pidgeys, Weedles, And Caterpies for Boosting....
This shouldn't even affect me?

**Comment by SamuriBakePie** [comment]
Can you guys explain to me what sniping is? From what I understand its teleporting like to  nest, but wouldn;t that tip off niantic?

**Comment by maartenpeels** [comment]
Why is this in the pull-request section? Please add it to issues tab with a clear explanation about what's not working. When it's added there, other developers will pick it up(probably), here it will get lost.

**Comment by ShallowHacker** [comment]
IDK where the hell that is... I added it because I couldn't find another section.

**Comment by Dano7** [comment]
@SamuriBakePie Sniping is teleporting to capture a specific pokemon, it almost certainly would tip-off Niantic... that it is not a phone app.   but it is an easy way to get rare pokemons, and for now it works!   knock-on-wood.

**Comment by ShallowHacker** [comment]
But it doesn't work. It just broke.

**Pull request closed without merging**
