### PR TITLE
How Can I Help?

### PR DESCRIPTION
**Pull request by garybracket**
Experienced with Powershell, VB Script, C#, VB, C++, want to help out if I can, anything I can do?

### CODE REVIEW

**Comment by msalinas69** [comment]
17:34:48] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.

How can i make this stop

**Comment by garybracket** [comment]
I'm pretty sure this is happening to everyone right now..

**Comment by zstraken** [comment]
I can confirm this, Happens when run from the Release or from the Source Code.

[19:39:56] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__19.MoveNext() in C:\Users\XXXXXXXX\Desktop\NecroBot-master\PoGo.NecroBot.Logic\Inventory.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__12.MoveNext() in C:\Users\XXXXXXXX\Desktop\NecroBot-master\PoGo.NecroBot.Logic\Inventory.cs:line 179
--- End of stack trace from previous location where exception was thrown ---

**Comment by timelf123** [comment]
@garybracket come to discord #development

**Pull request closed without merging**
