### PR TITLE
Improved handling for some edge cases with the maximum radius feature

### PR DESCRIPTION
**Pull request by Daylend**
A few users were confused when the program would endlessly list their highest Pokemon. This should hopefully fix that.

### CODE REVIEW

**Comment by qaqsd123** [comment]
Still keeps listing it. :(

**Comment by Daylend** [comment]
@qaqsd123 Does it at least give a warning saying there are no PokeStops nearby?

**Comment by qaqsd123** [comment]
Didn't get that far

**Comment by cvax** [comment]
This PR should not be accepted.

- `Coords.ini` is for easy configuration of GPS coordinates and overrides `DefaultLatitude/Longitude` in `UserSettings.settings`
- `Coords.ini`'s whole purpose is defeated if you are walking from `DefaultLatitude/Longitude` to `Coords.ini`.

The default values are only supposed to be used when Coords.ini GPS location provided by the user is invalid and broken. See Client.cs lines 50-60.

**Comment by Daylend** [comment]
Coords.ini is used to store the last location the bot was at. If limiting the distance was based on Coords.ini, it wouldn't be limiting the distance at all. It would only be able to travel to PokeStops x meters away from its current position, which is NOT what was intended. If you use the first coords found in Coords.ini, you would slowly drift away from your original position as the bot is reset, eventually having to put new coordinates in to keep the bot in the same place.

This PR prevents edge cases where you somehow get away from the predefined boundaries. This usually happens when a user forgets to clear their Coords.ini file before moving to a new start location as set in UserSettings.settings.

The point is to allow the user to save their position regardless of where they roam and continue where they left off, but keep them within a predefined area that doesn't change.

**Comment by cvax** [comment]
You are right. How about renaming Coords.ini to LastCoords.ini then to avoid confusion?

**Comment by Daylend** [comment]
Sure. Someone just needs to put up a PR. Feel free to if you'd like.

**Comment by cvax** [comment]
Also, if we are already going to walk back to the start, shouldn't we be spinning PokeStops along the way instead of just catching Pokemon? Could be a real long walk if someone was jumping across the country and didn't change both coords.

**Comment by Daylend** [comment]
Someone shouldn't be using this to walk across the country. This is for the cases where the bot is a minimal distance away from the radius. Otherwise they should see the message generated and restart the bot with the proper coordinates.

**Comment by ThomasSRL** [comment]
Dont worry @Daylend , it seems perfect as is! Hope it gets accepted!

**Pull request merged**
