### PR TITLE
Get Levelup Rewards

### PR DESCRIPTION
**Pull request by cawk**
This code works just fine 
if you want you can change the way it is displayed up to you?

### CODE REVIEW

**Comment by lorenzowalz** [comment]
@cawk So this eliminates the current issue where the inventory gets overloaded after leveling too many times (bot doesn't pick up those rewards)?

**Comment by cawk** [comment]
as far as i am aware when getting level rewards you will get all of the rewards even if your bag is full it will go over (this is just from my experience)

**Comment by PandaWalz** [comment]
@cawk That's what I was trying to say - that right now we get them but it overloads and won't throw the rewards away.

**Comment by Ilses** [comment]
@PandaWalz At least as of yesterday, I don't believe we even got them. Thus, they couldn't previously be thrown away.

**Comment by cawk** [comment]
@Ilses that is correct yes you would manually have to go on to the app and claim the rewards and you would miss some if you level up too quickly 
this claims them for you so no need to do anything

**Comment by Ilses** [comment]
Doesn't build for me with the current master.

**Comment by yamashi** [comment]
Yep this won't build, fix the build issues and you are in!

**Comment by kanfkasndklasdn** [comment]
I've patched it to build with master. ¿How can I help?

**Comment by kanfkasndklasdn** [comment]
Problem is that it recycles almost all that it receives

**Comment by bignuts** [comment]
that is normal beacause u have set max amount in settings, but this is useful for getting incubator, lucky eggs, lure ect without logging.

**Comment by cawk** [comment]
i will fix this for the latest version now wont take me too long to do so closing this for now

**Pull request closed without merging**
