### PR TITLE
add human-like behavior and randomization

### PR DESCRIPTION
**Pull request by thekjohn**
- random bearing and walk speed
- random delays
- short stops
- longer stops (rest) 

feel free to add configuration options for most changes

### CODE REVIEW

**Comment by panthernet** [comment]
should be optional

**Comment by thekjohn** [comment]
added configuration options

**Comment by Ehnoah** [comment]
Not sure, but we may should add a own Config File called HumanOptions.ini or some kind, I feel that the current config is quite ful yet.

**Comment by yamashi** [comment]
Very interesting but conflicts :(

**Comment by Spegeli** [comment]
humanizer are absolutely useless.

**Comment by yamashi** [comment]
think there was a PR to configure the delays

**Comment by thekjohn** [comment]
It is definitely not useless, also I added options, so everybody could choose his/her strategy.
Is there any way to get this PR merged to the master, or I should not try anymore ?

**Pull request closed without merging**
