### PR TITLE
Update logic.cs to showcase amount of candies

### PR DESCRIPTION
**Pull request by doggiekuk**
Amount of candies shown in DisplayHighest function descending.

### CODE REVIEW

**Comment by solenrus** [comment]
tested and working, thanks

**Comment by Antidote78** [comment]
Tested and it works!
candy

**Comment by Antidote78** [comment]
Maybe you could adapt it to show everytime you catch a pokemon
Just an idea but great job

**Comment by JoshYuen** [comment]
PR #468 also has a  similar implementation.

**Comment by yamashi** [comment]
Master is deprecated.

**Pull request closed without merging**
