### PR TITLE
[Feature] rename template

### PR DESCRIPTION
**Pull request by hakkotsu**
allow to set custom template string for renaming function

example:

``` json
"RenameTemplate": "{0}_{1}"
```

will output: Zubat_95

``` json
"RenameTemplate": "[{1}]{0}"
```

output: [95]Zubat

{0} - Pokemon name
{1} - IV

### CODE REVIEW

**Comment by GTXMike** [comment]
It looks great.

**Comment by mich3lam** [comment]
if (pokemonName.nameLength > nameLenght)

string does not contain defention for nameLengh

**Comment by hakkotsu** [comment]
@mich3lam what do you mean?
I just tested this brunch and did fresh compile and test run. Everything works

**Comment by hakkotsu** [comment]
I'm on it.

**Comment by hakkotsu** [comment]
I've spend some more time on this and figured out there was an unreachable block of code (since this task only runs if **RenameAboveIv** is true) and fixed a bug with empty name

Also now it's possible to rename Pokemons to their original name just by setting template to `"{0}"`

with IV:
img

original:
img

**Comment by GTXMike** [comment]
Thay what i was looking for. Thanks you took the idea on board and put it into the code.

**Comment by yamashi** [comment]
Will merge but conflicts :s

**Comment by 20giis** [comment]
hey guys, please where can I find the rename template? I've been looking and looking and I can't find it! I want to rename according  to my own wishes not with IV

**Pull request closed without merging**
