### PR TITLE
Google Refresh Token Value Fixed

### PR DESCRIPTION
**Pull request by decryptionz**
Fixed token ID value for new user's for authenticating Google Accounts

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
what should that fix?

**Comment by decryptionz** [comment]
The app.config value for google refresh token so people don't get kicked out of the authentication after 30 minutes

**Comment by NecronomiconCoding** [comment]
You dont get kicked out. The Auth Token is saved in appdata. Are you sure its the issue?

**Comment by decryptionz** [comment]
It's more for identification for new players? In ferox's build the value was identified in app.config for automatic login verification for google accounts

**Comment by decryptionz** [comment]
since there is two acronyms for authentication in app.config google and ptc. I saw this was messed up so i fixed it so you can take your token and replace SESSION and automatically login then having to put a code into google.com/device

**Pull request closed without merging**
