### PR TITLE
GUI / Removed Console + Settings Form

### PR DESCRIPTION
**Pull request by xX7**
Removed the console and created a simple GUI. The Console is now embed within the GUI.The Configs are also adjustable via a Settings - Form. Pretty plain right now but I will continue develop this. 
I hope you like it.

### CODE REVIEW

**Comment by darksoon** [comment]
have you screenies?

**Comment by sub7even** [comment]
Use WebSocket for GUI - this should remain console only!

**Comment by Linewalker** [comment]
The GUI looks like DetectiveSquirrel'. The map is missing: https://github.com/DetectiveSquirrel/Pokemon-Go-Rocket-API :-)

**Comment by ViezeVingertjes** [comment]
Development of this project is way too fast to maintain such a feature. For example, it's already waaaaayyyy behind as we speak, imagin how far it's behind by tomorrow. This renders it all useless as you have to edit the config manually anyway.

**Comment by xX7** [comment]
@ViezeVingertjes But if after every push, that would require a config setting, someone would create a label and an edit text and write 2 lines of code it wouldn't be actually that hard to keep it up to date... Same thing goes for the translations you can actually compare it.

**Comment by nicoschmitt** [comment]
The current direction of the official bot is more about keeping it in CLI and exposing websocket in order to decouple GUI and Logic. It may be the only way to keep up with the pace of dev.

**Comment by Linewalker** [comment]
You can setup a settings GUI automaticly. Takes some time, but works. Unfortunately this GUI looks a little strange, because every option is under another option. At least thats a way for just only keeping the languages up to date.

**Comment by ViBE-HU** [comment]
so a GUI is planned? it would be awesome. a Linux build too and i'm also interested in loco it.

**Comment by Emuuung** [comment]
Maybe make a different branch to work on the GUI, this way master branch would always remain as the main dev focus and the GUI branch would be an alternate choice to keep it along the line of master branch.

**Comment by ghosted2014** [comment]
hiya quick question how to i remove the reclying option ?

**Comment by ShawnHardwick** [comment]
As @ViezeVingertjes has said, once the features solidify a little more you will see us work on a GUI. We have already been discussing on when the best time would be to do a GUI. The majority of our users actually prefer the CLI for running multiple bots at once. Diverting devs over to the GUI would divide our attention on QoL and functional improvements.

I'm going to leave this open, but Im 95% sure this will be closed by a dev.

**Comment by romkazor** [comment]
@xX7 Its amazing. One question - when?!

**Comment by xX7** [comment]
@romkazor thank you! Worked 9h straight yesterday. Since NecroBot is now PokeMobBot I'll try to pull request it in PokeMobBot

**Comment by Kinsiinoo** [comment]
@xX7 
NecroBot =/= PokeMobBot
NecroBot is the official version :)

**Comment by xX7** [comment]
Yeah! @NecronomiconCoding is back :). I like the Idea about creating another branch. What do you think?

**Comment by Beltian** [comment]
@xX7 how about adding the ability for the console window to auto scroll?

Little annoying to have to scroll to keep up with the current status.

**Comment by NecronomiconCoding** [comment]
Websockets are still preferred

**Pull request closed without merging**
