### PR TITLE
Issue since last update

### PR DESCRIPTION
**Pull request by ManStache**
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: M. Path 'PtcUsername', line 4, position 18.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at PoGo.NecroBot.CLI.AuthSettings.Load(String path) in D:\Dev\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 44
   at PoGo.NecroBot.CLI.GlobalSettings.Load(String path) in D:\Dev\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 318
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in D:\Dev\NecroBot\PoGo.NecroBot.CLI\Program.cs:line 31

### CODE REVIEW

**Comment by kaeus** [comment]
This is not a valid PR...this is an issue, which were removed. You are probably missing valid quotes around your values in the config.

**Comment by hilycker** [comment]
While we're at it, could those "" be added by default? we would then avoid so many post like this both here and in discord

**Comment by Nothingst** [comment]
Is there someone have issue when necrobot run about 30min, it stopped working.  someone have the solution?

**Comment by xXxhp** [comment]
Have same problem with 30 min

**Comment by Yankees19** [comment]
The new update COMPLETELY destroyed the bot for me and no older versions work any longer. The sniper says it has caught me good pokemon, yet on the app, no pokemon caught from the sniper are there. To make it worse, the sniper managed to use all my pokeballs, great balls, and dozens of ultra balls. The .exe i used is gone and my efforts to obtain it again are exhausted. If someone has a working release folder i would appreciate it. If not, I guess I have to wait for Necronomicon to release a WORKING version. Thanks!

**Comment by Nothingst** [comment]
Someone has fixed the problem right now?  Version is not working after 30 min. Can't play game!!!!!!!!!!!!!  really need solution!!!!  I want to sleep~~~~

**Comment by dbw-holic** [comment]
@Yankees19 To my understanding, the increased use of advanced balls is expected when you have Sniper turned on. Looking at the logs on my screen when you sniper mons they are usually rare species, it appears to me that the current algorithm to increase the capture rate is using great balls or ultra balls when possible. So to my eye, that was expected behaviour as per the current algorithm.

**Comment by MarkHuangZ** [comment]
@Nothingst I have the same issure here. I have an untested solution which is easy.
1. Create a flat file call it "Start.bat" in the CLI Debug folder, which contains the NecroBot.exe.
2. Put following lines into the bat file:

:loop
START NecroBot.exe
TIMEOUT /T 1800 /NOBREAK
taskkill /fi "Windowtitle eq (Your Character ID)*"
goto loop
:exitloop

For example, taskkill /fi "Windowtitle eq RandomUser1177*"

What it does is start the bot when you run the script and start counting down for 30 mins and kills the bot process and restart it.

I don't know whether it works good or not but it might solve the problem just for this night.

**Comment by Yankees19** [comment]
@dbw-holic v0.3.2 doesn't work at all for me. Do you know what this error is? https://gyazo.com/a0a3d4bef5c3b7ec0fb26cf732ad0cca 
I have checked for errors in quotations and have found none so I am lost.

**Comment by xXxhp** [comment]
@MarkHuangZ if I have for example 3 running necro process will this script reload them too?

**Comment by Nothingst** [comment]
@MarkHuangZ  Thanks man!  I will try it and see it works or not

**Comment by dbw-holic** [comment]
@Yankees19 Is the file "log4net.dll" existing in the directory?

**Comment by MarkHuangZ** [comment]
@xXxhp You need to create 3 different bat file and put them into different folders. For example, Bot 1 using folder1, bot 2 using folder 2, and blahblah. Put 1 bat file in each folder and change your user ID inside the bat file will be good to use.

**Comment by MarkHuangZ** [comment]
@Nothingst Sure, I dont have time to test it for 30mins, cuz i am so tired right now... Gonna leave it like this. If this does not help. Please Google "bat loop" and "bat timer". This script is really easy to understand.

**Comment by xXxhp** [comment]
@MarkHuangZ tyvm =)

**Comment by Nothingst** [comment]
@MarkHuangZ  Thanks,  I also heard a solution:   just change "UseEggIncubators": true,  to false. 
I am not sure that work or not.  I will try it.

**Comment by Yankees19** [comment]
@dbw-holic Yeah its in the file. The bot was working fine a few hours ago and now it won't work even when I start with the freshly downloaded file.

**Comment by Shroomzie** [comment]
You idiots don't understand that you wont get any updates to the bot if you keep filling the pull request with impatient shit like this. Grow up, all of you.

**Comment by Yankees19** [comment]
@Shroomzie Correct me if I am wrong, my friend, but this pull request is named "issue since last update".

**Comment by MistahhJ** [comment]
@Yankees19 This whole section is for pull request. There was a whole section for issues, but y'all kept spamming in there so they removed it.

**Comment by Yankees19** [comment]
@MistahhJ Well I apologize then. I made my post because my bot turned to shit when the newest update came.

**Comment by Shroomzie** [comment]
Yankees19  not one of you have said you have code to push to fix it!!!!!! It is a code repository. you push wiki stuff or you push code. it is not for issues!

**Comment by Nothingst** [comment]
Acctually we just found the issues, and asked the solution for this.  Hope update!!!!!!!!

**Comment by Shroomzie** [comment]
Nothingst This is not the section to do so. You will eventually upset the people doing all the work for you then you will get nothing. Is that what you want? Backwards goofy cunts i swear.

**Comment by Nothingst** [comment]
@Shroomzie  don't say that, I think all of you want to get solution when it has issues. not just talk about other

**Comment by rawkus123** [comment]
I agree with @shroomzie... it's not like anyone paid for the bot. Like he said the bot stopped working 1 hour ago... wait till its fixed and go outside like pokemon go was designed for lol

**Comment by syzswag** [comment]
Sorry guys, probably is not the right section but is there any way to keep with the version 0.1.9. sry for bad englando.
If someone can help i would be grateful add skype if possible. skype: diogo.silva343
Sorry!

**Comment by Shroomzie** [comment]
Discord channel on the main page! @syzswag

**Comment by IstenesImre** [comment]
Sry, cant open new thread.

Its a transfer bug or feature?

[08:05:27] (TRANSFERED) Paras   - CP: 313  IV: 39,59%   [Best CP: 298  IV: 78,86%] (Candies: 42)

thx

**Comment by lotusJDM** [comment]
@Shroomzie Is it just me or does the invite link on the main page doesn't work?

**Comment by maxleveling** [comment]
I am sorry i want to ask, why i running 3 hour  but  didnt get any monster from sniping.
No single dratini or magicrap i get.

[13:13:02] [Sniper] Scanning for Snipeable Pokemon at 38,5568074864611,-121,238379478455...
[13:13:02] [Sniper] No Pokemon found to snipe!
[13:13:02] [Sniper] Scanning for Snipeable Pokemon at -33,859019,151,213098...
[13:13:03] [Sniper] No Pokemon found to snipe!
[13:13:03] [Sniper] Scanning for Snipeable Pokemon at 47,5014969,-122,0959568...
[13:13:03] [Sniper] No Pokemon found to snipe!
[13:13:03] [Sniper] Scanning for Snipeable Pokemon at 51,5025343,-0,2055027...
[13:13:04] [Sniper] No Pokemon found to snipe!

This is my config
"AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.785091,
  "DefaultLongitude": -73.968285,
  "DelayBetweenPokemonCatch": 2000,
  "DelayBetweenPlayerActions": 5000,
  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseEggIncubators": true,
  "DumpPokemonStats": false,
  "GpxFile": "GPXPath.GPX",
  "UseGpxPathing": false,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxTravelDistanceInMeters": 1000,
  "KeepMinCp": 1250,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "PrioritizeIvOverCp": false,
  "RenameAboveIv": false,
  "RenameTemplate": "{0}_{1}",
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": true,
  "SnipeAtPokestops": true,
  "ItemRecycleFilter": [
.
.
.
 },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "Dratini",
      "Magikarp",
      "Eevee",
      "Charmander"
    ]
  }
}

there is something wrong with my config ??? thk u before

**Comment by Asentrixx** [comment]
@lotusJDM You're banned from it, that's why

**Comment by lotusJDM** [comment]
@Asentrixx What the hell? Then how do you get unbanned.

**Comment by ArionMiles** [comment]
I have found the solution. 
Cross checking with the old `auth.config` file, I found that the Username and Password need to be in double quotes in the below format:

`"ptcUsername": "foo",
"ptcPassword": "bar"`

**Comment by RoSeawolf** [comment]
Sorry for posting here, but after the new update i got this problem with Transferring :
mstsc_2016-07-29_09-38-05

**Comment by maxleveling** [comment]
@roseawoft:
edit your config
"PrioritizeIvOverCp": true,
to
"PrioritizeIvOverCp": false,

**Comment by lotusJDM** [comment]
@RoSeawolf Yeah because IV>CP is the best option if you want perfect monsters

**Comment by CakeOrCrayons** [comment]
Any fix on the 30 minute timeout? Besides the .bat loop?

**Comment by brama23** [comment]
@CakeOrCrayons yes im too

**Comment by MyBad2512** [comment]
@maxleveling : Same issue here, bot isnt sniping any Mon. You got it fixed?
[09:00:17] [Sniper] Scanning for Snipeable Pokemon at 38,556558,-121,235678...
[09:00:18] [Sniper] No Pokemon found to snipe!

**Comment by N4MeD** [comment]
@MarkHuangZ what is the character id ?

**Comment by N4MeD** [comment]
@MarkHuangZ is it the process id in the taskmanager ?

**Comment by N4MeD** [comment]
Can anyone answer ?

**Comment by rastinder** [comment]
i hv 6 acc running n this 30 min prob came in every acc except my main acc
so this is my config file test it . hope this works
{
  "AmountOfPokemonToDisplayOnStart": 20,
  "AutoUpdate": true,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 34.008849783443793,
  "DefaultLongitude": -118.49635720252992,
  "DelayBetweenPokemonCatch": 1,
  "DelayBetweenPlayerActions": 1,
  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseEggIncubators": true,
  "DumpPokemonStats": false,
  "GpxFile": "GPXPath.GPX",
  "UseGpxPathing": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "MaxTravelDistanceInMeters": 1000,
  "KeepMinCp": 1250,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "PrioritizeIvOverCp": true,
  "RenameAboveIv": true,
  "RenameTemplate": "{0}_{1}",
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "SnipeAtPokestops": true,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 10
    },
    {
      "Key": "itemHyperPotion",
      "Value": 40
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "aerodactyl",
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo",
    "goldeen",
    "paras",
    "ekans",
    "staryu",
    "psyduck",
    "krabby",
    "venonat"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Zubat": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Pinsir": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golduck": {
      "KeepMinCp": 1350,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Tentacruel": {
      "KeepMinCp": 1350,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Starmie": {
      "KeepMinCp": 1350,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 750,
      "KeepMinIvPercentage": 92.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Gyarados": {
      "KeepMinCp": 1200,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 5
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.542805143765207,
        "Longitude": -121.27775430679321
      },
      {
        "Latitude": 38.552481550341355,
        "Longitude": -121.23799324035645
      },
      {
        "Latitude": 38.544282029499193,
        "Longitude": -121.23490333557128
      },
      {
        "Latitude": 34.008604317461234,
        "Longitude": -118.4968400001526
      },
      {
        "Latitude": -34.003854945044871,
        "Longitude": -118.4907031059265
      },
      {
        "Latitude": 33.9877513508259,
        "Longitude": -118.47295761108398
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 34.046202139972358,
        "Longitude": -118.24705123901366
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "Dratini",
      "Magikarp",
      "Eevee",
      "Aerodactyl",
      "Arcanine",
      "Charizard",
      "Dragonite",
      "Exeggutor",
      "Exeggcute",
      "Growlithe",
      "Gyardos",
      "Lapras",
      "Mr.mime",
      "Pikachu",
      "Porygon",
      "Snorlax",
      "Tauros",
      "Vaporeon",
      "Charmander"
    ]
  }
}

**Comment by N4MeD** [comment]
I figured out that u have to write the players name there

**Comment by mochdev** [comment]
how to disable snipe feature? please help
since update snipe feature my acc always have no pokeball
and snipe feature make lvl up longer.

help please

**Comment by iKayx** [comment]
@mochdev just Delete Locations and Pokemon from the Config like this:

"PokemonToSnipe": {
"Locations": [],
"Pokemon": []
}

**Comment by Kivoou** [comment]
@iKayx What exactly does the Snipe feature do? The default input shows four completely different places. I deactivated the feature before the first login. As much as I know you can't just move to different places as this would earn you a soft ban? What's the exact purpose?

**Comment by rezarizky90** [comment]
what if error like this?

[17:21:30] Logging in using Google
[17:21:30] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DankMemes.GPSOAuthSharp.GoogleKeyUtils.ParseAuthResponse(String text)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 17
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 30
--- End of stack trace from previous location where exception was thrown ---

**Pull request closed without merging**
