### PR TITLE
Online Sniper Server

### PR DESCRIPTION
**Pull request by Tsuki**
Add to use Sniper server

Just copy from http://pokesnipers.com/ and paste to the server console.

It will send to bot socket

### CODE REVIEW

**Comment by jaskovic** [comment]
how can i add this in mine necro bot?

**Comment by tangdami** [comment]
This looks great! Yes, how can we add this? Thank you!

**Comment by Tsuki** [comment]
Still in testing

**Comment by henbas** [comment]
got any results? cant wait to see sniping in full automatic action :-)

**Comment by Tsuki** [comment]
Just have another idea from @henbas 
this function will work leater

**Comment by actisys** [comment]
http://pokesnipers.com/api/v1/pokemon.json

i saw plenty sniper bot getting from this already :) .. keep the good work.. support!

**Comment by streppelchen** [comment]
maybe i'd suggest to keep the tcp session to the snipeserver alive, so you don't have to transmit the same information over and over again, since the server could then implement a logic to remember which client has which information. else make the bot send a unique token to identify it. just an idea ofc.

**Comment by jaskovic** [comment]
hee guys how to put in that Discord server channels for sniping.
for necro bot?

**Comment by Tsuki** [comment]
Just updated and work properly

**Comment by Tsuki** [comment]
image

**Comment by koubie** [comment]
How to make the sniping work in the  Compiled Release Setup version?

**Comment by Tsuki** [comment]
You can pick my commit and Compiled

**Comment by actisys** [comment]
I'm using the released version, can you help?

**Comment by koubie** [comment]
but there is nothing u can modify in the Compiled Release Setup version. its a ready-to-go version for noob people

**Comment by Tsuki** [comment]
[Download](https://github.com/Tsuki/NecroBot/releases/download/v0.4.1/NecroBot.exe)

Some config need to update


  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "UseSnipeLocationServer": true,

**Comment by Tsuki** [comment]
I just rebase to the 4.0 version, it is safe to test this build

**Comment by aeryl1999** [comment]
do i leave these untouched?
"SnipeLocationServer": "localhost",
 "SnipeLocationServerPort": 16969,
"UseSnipeOnlineLocationServer": false

**Comment by Tsuki** [comment]
"UseSnipeOnlineLocationServer": true should added

**Comment by Tsuki** [comment]
Also there another problem.
If snip to fast the bot will re-snip the old record.

**Comment by irishneil** [comment]
im getting this error after following ur instructions
https://s31.postimg.org/6dtgk92qj/Capture.png
please help, excellent work!

**Comment by irishneil** [comment]
also its asking for auth etc i have all that setup

**Comment by henbas** [comment]
works for me thanks a lot @Tsuki !

**Comment by Tsuki** [comment]
try to remove the config.json and let it rebuild

**Comment by aeryl1999** [comment]
The sniper is indeed using pokesnipers but it just says No Pokemon Found to Sniper

**Comment by Tsuki** [comment]
It it because you config have filter it

modify it in "PokemonToSnipe": { >>>>>"Pokemon": [

**Comment by aeryl1999** [comment]
adding, thanks again

**Comment by irishneil** [comment]
ok shit, missed the coma after true, seems to be running now

**Comment by Tsuki** [comment]
no more pokeball in the bag,

It keep snipe haha @

**Comment by koubie** [comment]
snapshot_2016-07-30_151521
Its been running but NO SNIPE :(

**Comment by irishneil** [comment]
Didnt seem to be sniping so i changed it to what u said,

https://s32.postimg.org/mdiwv9451/Capture.png

Getting Error on boot.

https://s32.postimg.org/mtolia1md/Capture.png

edit, changed due to same reason as guy above

**Comment by RivalzZz88** [comment]
same here, no sniping ... i added some long-lat to the config, how it will work when the config get the information from the server ?

**Comment by Tsuki** [comment]
I seem that you having enable sniping
if yes, you will see  a lot of (INFO) [Sniper] Sniping a "PKM"

**Comment by irishneil** [comment]
can u post the correct config file please to test

**Comment by Tsuki** [comment]
Here you are.
[config.zip](https://github.com/NecronomiconCoding/NecroBot/files/392128/config.zip)

**Comment by actisys** [comment]
the only different is "UseSnipeOnlineLocationServer": true 
must set it to true. cheers.. its working now .. thanks

**Comment by RivalzZz88** [comment]
when i add the UseSnipeOnlineLocationServer value to the config it won't be there at starting the bot again, it will removed... how i fix it ?

**Comment by irishneil** [comment]
working now thanks alot :D

https://s32.postimg.org/6akjl4gz9/Capture.png

**Comment by moredhel92** [comment]
Good Job Tsuki

**Comment by actisys** [comment]
By the way, when met "System.AggregateException: One or more errors occured --> 
The bot will auto restart then my lat and lng will change to the sniping location.

**Comment by Tsuki** [comment]
If any config issues please try to remove the config.json and let the bot rebuild it
then update the config you need

**Comment by actisys** [comment]
omg, i just caught this Snorlax Lvl: 7 CP: (606/607) IV: 99.00% ...  but i need a lot stardust to power up lol..

**Comment by moredhel92** [comment]
http://prntscr.com/bzmnhl

**Comment by Tsuki** [comment]
CatchSuccess Attempt #3) | (Normal) Snorlax Lvl: 27 CP: (2397/2401) IV: 99.00% I also got it

**Comment by irishneil** [comment]
got it too 606

**Comment by moredhel92** [comment]
i use this pages too
https://www.facebook.com/LaprasSpawns/
https://www.facebook.com/DragoniteSpawns/
https://www.facebook.com/snorlaxspawns/

**Comment by actisys** [comment]
the pokemon snipe filter seems doesn't affect any of your sniper script.

**Comment by Tsuki** [comment]
It it white list filter, @actisys

**Comment by Cuuup** [comment]
@Tsuki  how can i implement this into my release files?

**Comment by actisys** [comment]
@Tsuki what do you mean?

**Comment by Zombsle** [comment]
Somehow i dont get it to run. Can someone please give me a step by step guide to get it running?

**Comment by Oolaruu** [comment]
Will this be implemented into the main NecroBot ?

**Comment by RivalzZz88** [comment]
i deleted the config for 3 times but every time when it will regenerated theres no "UseSnipeOnlineLocationServer": true  inside :/

**Comment by actisys** [comment]
It's at the bottom line. @RivalzZz88

**Comment by RivalzZz88** [comment]
"UseMasterBallAboveCp": 1500,
  "UsePokemonToNotCatchFilter": false,
  "UseSnipeLocationServer": false,
  "UseTransferIvForSnipe": false,
  "UseUltraBallAboveCp": 1000,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "WebSocketPort": 14251
}

thats the end :/

**Comment by irishneil** [comment]
are you blind with excitement man, 3rd one down on ur list

**Comment by Cuuup** [comment]
@RivalzZz88 download this [https://github.com/Tsuki/NecroBot/releases/download/v0.4.1/NecroBot.exe](url)

and put that into your compilied release file.
delete your config
and change everything as needed and it should run

**Comment by henbas** [comment]
simply insert the code

**Comment by actisys** [comment]
@RivalzZz88 you have to download the file by @Tsuki  .. then remove your older config then fresh restart by opening the .exe file (be sure overwrite or remove the older .exe)

**Comment by Cuuup** [comment]
@Tsuki Great work! Thanks for this ! Much appericated and working as intended

**Comment by RivalzZz88** [comment]
Cheers ! now its inside ;-) now i give it a try, thanks guys, you rock!

**Comment by desfoi** [comment]
Is it possible to use the two methods?
Like, the server, and the old one.
I really like how it snipes rarer Pokemon than with the other method, but with the other, I already had some nice spots to get magicarps, charmanders and dratinis xD

**Comment by moredhel92** [comment]
dratinis where???

**Comment by irishneil** [comment]
+1 dratinis where???

**Comment by desfoi** [comment]
was getting them here xD
Latitude	37.808966
Longitude	-122.410153

and

Latitude	37.802035
Longitude	-122.396814

but I'm not sure if with the changes in the nests they will continue to spawn as they used to...

**Comment by moredhel92** [comment]
i found other sniper for coordinates and specific pokemon
and nests dratini are now eevee xD

**Comment by irishneil** [comment]
@Tsuki can we have drantini added to the list of pokemon ? :D

**Comment by RivalzZz88** [comment]
01:31:13] (CatchSuccess) | (Normal) Snorlax Lvl: 26 CP: (2113/2312) IV: 35.00% | Chance: 11.74% | 1434256.81m dist | with a UltraBall (91 left). | Candies: 6

got it 8) nice guys ^^

**Comment by mochdev** [comment]
@Tsuki  is there any filter for sniping with pokeSnipers? what the mean of with 100 IV? 
and why its only sniping, doesnt cacth the pokemon?

**Comment by koubie** [comment]
snapshot_2016-07-30_163522
So,
I follow the step and set  the SnipeLocationServer: false and the OnlineLocationServer: true and it doesnt work? should I set both TRUE? 
"UseSnipeLocationServer": false,
  "UseTransferIvForSnipe": false,
  "UseUltraBallAboveCp": 1000,
  "WalkingSpeedInKilometerPerHour": 30.0,
  "WebSocketPort": 14251,
  "UseSnipeOnlineLocationServer": true

**Comment by moredhel92** [comment]
usesnipelocationserver: true

**Comment by RivalzZz88** [comment]
what does the "UseTransferIvForSnipe": false, doing if i set it on true ?

**Comment by actisys** [comment]
"SnipeAtPokestops": true,
"SnipeIgnoreUnknownIv": true,
"UseSnipeLocationServer": true
"UseSnipeOnlineLocationServer": true

**Comment by tangdami** [comment]
Wow!! Thanks for @Tsuki 's hard work! It works flawlessly with the online sniper.
Any idea any difference between these two? I made them as true... (I know the second one was based on http://pokesnipers.com/, but the first....?)

"UseSnipeLocationServer": true
"UseSnipeOnlineLocationServer": true

**Comment by koubie** [comment]
UseTransferIvForSnipe (Value)

When UseTransferIvForSnipe is set to true, Necrobot will use the the global KeepMinIvPercentage value and PokemonTransferFilter list to determine if it should attempt to snipe a Pokemon.

**Comment by RivalzZz88** [comment]
is this an good option or not? where is the List to check?

All the best ;)

**Comment by irishneil** [comment]
anyway to add in dratini's and maybe a filter ppl that dont want it filling up the list, :D :D

**Comment by Sylencer90** [comment]
Any chance getting this into the official necro release in the next hour?

**Comment by moredhel92** [comment]
discord its ok?

**Comment by Regerta** [comment]
Is someone can make snipe scanner with skiplagged api?
https://skiplagged.com/pokemon/
I guess that's better than pokevision

Thanks,

**Comment by junaidd007** [comment]
Yeah use  skiplagged.com.

**Comment by junaidd007** [comment]
Idk why pokevision.com uses ptc. Google is much better

**Comment by kfein666** [comment]
there no Compiled Release  in the dowload section? i fucked up my file and want to restart from scratch

**Comment by AriSrijaya** [comment]
release update new compilasi please

**Comment by AriSrijaya** [comment]
@Tsuki can you add Dratini in the server or magicarp
I need the candy to evo and level up

**Comment by Thaku** [comment]
Does anyone have the correct settings for a working "UseSnipeLocationServer"?

My settings are as below: Can anyone help? :( My snipe are not working and not showing up on the text itself.

{
"AmountOfPokemonToDisplayOnStart": 10,
"AutomaticallyLevelUpPokemon": false,
"AutoUpdate": true,
"DefaultAltitude": 10.0,
"DefaultLatitude": 51.496249,
"DefaultLongitude": -0.110105,
"DelayBetweenPlayerActions": 500,
"DelayBetweenPokemonCatch": 200,
"DumpPokemonStats": false,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": true,
"GpxFile": "GPXPath.GPX",
"ItemRecycleFilter": [
{
"Key": "itemUnknown",
"Value": 0
},
{
"Key": "itemLuckyEgg",
"Value": 200
},
{
"Key": "itemIncenseOrdinary",
"Value": 100
},
{
"Key": "itemIncenseSpicy",
"Value": 100
},
{
"Key": "itemIncenseCool",
"Value": 100
},
{
"Key": "itemIncenseFloral",
"Value": 100
},
{
"Key": "itemTroyDisk",
"Value": 100
},
{
"Key": "itemXAttack",
"Value": 100
},
{
"Key": "itemXDefense",
"Value": 100
},
{
"Key": "itemXMiracle",
"Value": 100
},
{
"Key": "itemRazzBerry",
"Value": 50
},
{
"Key": "itemBlukBerry",
"Value": 10
},
{
"Key": "itemNanabBerry",
"Value": 10
},
{
"Key": "itemWeparBerry",
"Value": 30
},
{
"Key": "itemPinapBerry",
"Value": 30
},
{
"Key": "itemSpecialCamera",
"Value": 100
},
{
"Key": "itemIncubatorBasicUnlimited",
"Value": 100
},
{
"Key": "itemIncubatorBasic",
"Value": 100
},
{
"Key": "itemPokemonStorageUpgrade",
"Value": 100
},
{
"Key": "itemItemStorageUpgrade",
"Value": 100
}
],
"KeepMinCp": 1250,
"KeepMinDuplicatePokemon": 1,
"KeepMinIvPercentage": 90.0,
"KeepPokemonsThatCanEvolve": false,
"LevelUpByCPorIv": "iv",
"MaxPokeballsPerPokemon": 6,
"MaxSpawnLocationOffset": 10,
"MaxTravelDistanceInMeters": 100000,
"MinDelayBetweenSnipes": 60,
"MinPokeballsToSnipe": 30,
"MinPokeballsWhileSnipe": 1,
"PokemonsNotToTransfer": [
"venusaur",
"charizard",
"blastoise",
"nidoqueen",
"nidoking",
"clefable",
"vileplume",
"arcanine",
"poliwrath",
"machamp",
"snorlax",
"victreebel",
"golem",
"slowbro",
"muk",
"exeggutor",
"lickitung",
"chansey",
"ditto",
"articuno",
"zapdos",
"moltres",
"mewtwo",
"mew"
],
"PokemonsToEvolve": [
"caterpie",
"weedle",
"pidgey",
"rattata"
],
"PokemonsToIgnore": [
"caterpie",
"weedle",
"rattata",
"spearow",
"zubat",
"doduo"
],
"PokemonsTransferFilter": {
"Golduck": {
"KeepMinCp": 1800,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 1
},
"Farfetchd": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 80.0,
"KeepMinDuplicatePokemon": 1
},
"Krabby": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 1
},
"Kangaskhan": {
"KeepMinCp": 1500,
"KeepMinIvPercentage": 60.0,
"KeepMinDuplicatePokemon": 1
},
"Horsea": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 1
},
"Staryu": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 1
},
"MrMime": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 40.0,
"KeepMinDuplicatePokemon": 1
},
"Scyther": {
"KeepMinCp": 100,
"KeepMinIvPercentage": 80.0,
"KeepMinDuplicatePokemon": 1
},
"Jynx": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 1
},
"Electabuzz": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 80.0,
"KeepMinDuplicatePokemon": 1
},
"Magmar": {
"KeepMinCp": 1500,
"KeepMinIvPercentage": 80.0,
"KeepMinDuplicatePokemon": 1
},
"Pinsir": {
"KeepMinCp": 1800,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 1
},
"Tauros": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1
},
"Magikarp": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 2
},
"Gyarados": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1
},
"Lapras": {
"KeepMinCp": 1800,
"KeepMinIvPercentage": 80.0,
"KeepMinDuplicatePokemon": 2
},
"Eevee": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 3
},
"Vaporeon": {
"KeepMinCp": 1500,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1
},
"Jolteon": {
"KeepMinCp": 1500,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1
},
"Flareon": {
"KeepMinCp": 1500,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1
},
"Porygon": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 60.0,
"KeepMinDuplicatePokemon": 1
},
"Snorlax": {
"KeepMinCp": 2600,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 2
},
"Dragonite": {
"KeepMinCp": 2600,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 2
}
},
"PokemonToSnipe": {
"Locations": [
{
"Latitude": -33.83625087,
"Longitude": 151.123434988
},
{
"Latitude": 52.5211332091,
"Longitude": 13.2960010112
},
{
"Latitude": -33.859019,
"Longitude": 151.213098
},
{
"Latitude": 35.7063946031,
"Longitude": 139.68806646
},
{
"Latitude": 51.514339,
"Longitude": -0.118023
},
{
"Latitude": 41.7453950624,
"Longitude": -87.6210675459
},
{
"Latitude": 41.7596760152,
"Longitude": -87.5753843807
},
{
"Latitude": 51.5071473182,
"Longitude": -0.206622934525
},
{
"Latitude": 51.5065548597,
"Longitude": -0.0905533113428
}
],
"Pokemon": [
"snorlax",
"dragonair",
"aerodactyl",
"dratini",
"pidgey",
"squirtle",
"charmander",
"growlithe",
"exeggcute",
"mew"
]
},
"PokemonToUseMasterball": [
"articuno",
"zapdos",
"moltres",
"mew",
"mewtwo"
],
"PrioritizeIvOverCp": true,
"RenameOnlyAboveIv": true,
"RenamePokemon": false,
"RenameTemplate": "{1}_{0}",
"SnipeAtPokestops": false,
"SnipeIgnoreUnknownIv": false,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
"StartupWelcomeDelay": false,
"TotalAmountOfPokebalsToKeep": 350,
"TotalAmountOfPotionsToKeep": 1,
"TotalAmountOfRevivesToKeep": 1,
"TransferConfigAndAuthOnUpdate": true,
"TransferDuplicatePokemon": true,
"TranslationLanguageCode": "en",
"UpgradePokemonCpMinimum": 1000.0,
"UpgradePokemonIvMinimum": 95.0,
"UseEggIncubators": true,
"UseGpxPathing": false,
"UseGreatBallAboveCp": 750,
"UseLuckyEggsMinPokemonAmount": 30,
"UseLuckyEggsWhileEvolving": false,
"UseMasterBallAboveCp": 1500,
"UsePokemonToNotCatchFilter": false,
"UseSnipeLocationServer": true,
"UseTransferIvForSnipe": false,
"UseUltraBallAboveCp": 1000,
"WalkingSpeedInKilometerPerHour": 15.0,
"WebSocketPort": 14251,
"UseSnipeOnlineLocationServer": false
}

**Comment by eLyiN** [comment]
` "UseSnipeOnlineLocationServer": false` to true

**Comment by Thaku** [comment]
Thanks ELyiN, I found it odd that this type of sniping doesn't work with the latest release 0.4.0. I am running version 0.3.3 and it is now working.. Very odd!

**Comment by Sylencer90** [comment]
Can we get a released version with this already added in? The latest release misses the "UseSnipeOnlineLocationServer":    line for me, just adding the line wouldn't do a god damn thing right :D?

**Comment by TheHaliax** [comment]
this is great but this is only sniping rare pokemon which isn't good for exp/h, anyway can we get https://github.com/AHAAAAAAA/PokemonGo-Map integrated into the pokesniping? this way the we could potentially set up our own sniping locations without the snipeatstop functionality breaking every other release?

**Comment by TheHaliax** [comment]
@sylencer90 when you run @Tsuki compiled it will update your config so all you need to do is set that value to true and you'll be good.

**Comment by dsmad** [comment]
in 0.4.0 i can still get the snipe, but its just really rare and rarely succeed, and the snipes arent really rare pokemons.

or is the snipe based on an RNG?

**Comment by tangdami** [comment]
Sniper was working well for me. But I think I sometimes teleported me to the sniper location, and then the bot just starts to walk back to the original location which is 9070129 meters away.....

image

**Comment by koubie** [comment]
Hi @Tsuki can you make the new downloadable compiled file Necrobot.exe for the new update v0.5.5 ?
the snipe doesn't work anymore in the new update
Thank you

**Comment by dsmad** [comment]
hi, i would like to ask in v0.5.0 why my ultra ball is always used  to catch pidgeys and pokemons below 1000 CP?

**Comment by AriSrijaya** [comment]
@tsuki update on 5.0 base please

**Comment by AriSrijaya** [comment]
@Tsuki can you make the new downloadable compiled file Necrobot.exe for the new update v0.5.0 base?

or anyone can help me?|
cause in new update i cant snipe :(

**Pull request merged**
