### PR TITLE
Yamashi Is So Salty

### PR DESCRIPTION
**Pull request by OverlordQ**

### CODE REVIEW

**Comment by OverlordQ** [comment]
It's okay, we forgive you.

**Comment by mich3lam** [comment]
@OverlordQ It's either you are stupid like a monkey or you are drunk af and you should go sleep

**Comment by OverlordQ** [comment]
Not my fault he got so salty over being called out for his laziness.

**Comment by mich3lam** [comment]
@OverlordQ Do you understand how many commits he reads? How many work he has? How many things he need to fix because people like you are stupid af?

ok bye

**Comment by OverlordQ** [comment]
Then he should leave it to somebody else

**Comment by mGeek** [comment]
Stfu @OverlordQ.
There is a reason why the devs have closed the issues and I think you, all by yourself, is a reason.
So open an issue in your little brain and go to sleep.

**Comment by Deske043** [comment]
How can u call him lazy..

**Comment by Deske043** [comment]
He's doing all this for free 2 help the community u dick

**Comment by hilycker** [comment]
Whatever you think, it doesn't allow you to spam PR section or go againts rules and/or netiquette. So put this to an end thank you.

**Pull request closed without merging**
