### PR TITLE
Rename all pokemon with IV that aren't already nicknamed.

### PR DESCRIPTION
**Pull request by Sekioh**
Resolved conflicts for #1325.

### CODE REVIEW

**Comment by solenrus** [comment]
great stuff!

**Comment by DeadElle** [comment]
approved +1

**Comment by sub7even** [comment]
May you can add an option to rename all Pokemon (and not only the ones that aren't already nicknamed)?

I'd  like to change the Naming format and in this case I need to update all Pokemon (including the one who already have a nickname).

**Comment by Sekioh** [comment]
Naming format is already supported by the newer revisions under the translation files. I'll consider changing the flag from toggle to a string like "All", "Original", "MinimumIV". Then people can pick from options.

**Comment by Ryuichiro** [comment]
I created a very similar solution, but I think it should be easier to extend and I added a skip for favorites.
[#1431](https://github.com/NecronomiconCoding/NecroBot/pull/1431)

**Comment by NecronomiconCoding** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
