### PR TITLE
Fix stoping after 30min 

### PR DESCRIPTION
**Pull request by chuuddo**

### CODE REVIEW

**Comment by rezarizky90** [comment]
can i ask what if error like this?

[17:21:30] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DankMemes.GPSOAuthSharp.GoogleKeyUtils.ParseAuthResponse(String text)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 17
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 30

**Comment by f998601** [comment]
delete auth.conf under /botfolder/config and then login into google from beginning. your google token is not valid.

**Comment by rezarizky90** [comment]
I just use releases necrobot v3.0.2.
So what can i do to fix that?

**Comment by eukaristia** [comment]
login with ptc is same, 30 min bot stop

**Comment by chuuddo** [comment]
@eukaristia, i send pr 20 min ago and u already tested this? dont think so.

**Comment by hche608** [comment]
@chuuddo I have tested code, does not fix the problem, I think the problem is renew the token from google

**Comment by Lennix3** [comment]
@chuuddo  I have the same Problem with PTC. The Bot stops working after 30 Minutes.

**Comment by chuuddo** [comment]
@Lennix3 i just test this with PTC. 
ptc
This fix only restarting bot after 30 min.

If u have problems with login, try to update FeroxRev submodule.

**Comment by Rozzla** [comment]
Bonjour, j'ai actuellement le même soucis, le bot fonctionne mais crash au bout de 30 minutes sans aucunes erreur, je pense à un problème de token google.

- - - 

Hello, i have the same pronlem, the bot is good running but he crash in 30mn without error, i think is an error of the google token.

**Comment by Lennix3** [comment]
@chuuddo Can you tell me how can i download the fix, login works but it stops after 30 minutes with ptc. Im new on Github sry.

**Comment by Colwyn29** [comment]
Leave this idea of Access Token, i have a ptc and google account running in same time and this issue appears on each account.

**Comment by chuuddo** [comment]
@rozzla i think Pokemon Go server drop connection after 30min, that's why bot got exception and stops working,

**Comment by chuuddo** [comment]
@Lennix3 u can clone from https://github.com/chuuddo/NecroBot and compile yourself

**Comment by rammydesi** [comment]
@chuuddo experiencing the same issue

**Comment by Lennix3** [comment]
@chuuddo If you could compile it for all those people which have the problem would be nice, because im to stupid for this and only know java.

**Comment by Sylencer90** [comment]
Can some1 fix this please?

**Comment by weespin** [comment]
@chuuddo One of my bot has worked for 5 hrs before he freezed like a 30 min bug.

**Comment by LoloLaurentiu** [comment]
I hate the same issue. I guess I'l just wait for the next update.

**Comment by 089flo** [comment]
How about writing a Kill-Restart-Batch.. i try out a bit, but sorry my Kung-Fu-Level is to low to make something useful.

**Comment by TNXNgoc** [comment]
Same! PTC account too!
BOT stop after 30mins use!

**Comment by MadEyez** [comment]
@089flo [here you are](https://github.com/NecronomiconCoding/NecroBot/compare/v0.3.2...master#commitcomment-18443841)

**Comment by Rozzla** [comment]
FIX : 

Go to "config.json" and go to >> "StartupWelcomeDelay": false,

and put this file in your folder and execute ;) 

https://mega.nz/#!9wknlYjS!mVNLdCeT7yalFHoGfwW1AAO76XXJDj8o42iCDbJLZh8

**Comment by TheWura** [comment]
I have the same issue. I use PTC Account and after 30 min, the bot stops working.

**Comment by InnerFire** [comment]
It keeps walking though :-p

**Comment by InnerFire** [comment]
I just re-implemented the same version. (Deleted new one and started new one with same config.)

Will work for 30 mins and then repeat the same again.

**Comment by Tomabl** [comment]
As someone has written before: An easy "fix" would be to create run.bat file with this code:

@echo off
:loop
start NecroBot.exe
timeout /t 1800 >null
taskkill /f /im NecroBot.exe >null
timeout /t 120 >null
goto loop

The run.bat file should be saved in the folder, where your exe is located. The bat-file closes the exe after 30 minutes and after 2 minutes executes it (it is a loop). Sorry I'm not really into coding, but I hope this can help (not my credits, I've seen this code somewhere here.

**Comment by aVitomin** [comment]
@Tomabl http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/563133-necronomicons-bot-163.html#post3496087 )))

**Comment by yamashi** [comment]
This is fixed in 0.3.3

**Comment by N4MeD** [comment]
I think v0.3.3 fixes it

**Pull request closed without merging**
