### PR TITLE
Important Snipes

### PR DESCRIPTION
**Pull request by mich3lam**

### CODE REVIEW

**Comment by ifbatmanwasreal** [comment]
Does this work? Have you tested? Because when I add too many to the snipe list it doesn't work correctly.

**Comment by mich3lam** [comment]
@ifbatmanwasreal lol yes it works

**Comment by ShallowHacker** [comment]
How do I input? It looks different lol

**Comment by ifbatmanwasreal** [comment]
He changed the way they are identified. Just follow copy his and replace it with your old. And then follow his format if you add Pokemon to the list.

That's the quickest way.

**Comment by Yodude12** [comment]
he meant which file should he put these new pokemon in since we were only using the notepad to edit ... right ??

**Comment by ShallowHacker** [comment]
Nah, I know.

Right into the config with Notepad++

**Pull request merged**
