### PR TITLE
Websocket: Allow Pokemon Transfer from the GUI

### PR DESCRIPTION
**Pull request by nicoschmitt**

### CODE REVIEW

**Comment by Aneduna** [comment]
What did you change other that EventDispacer in the last commit?

**Comment by nicoschmitt** [comment]
There was a try catch used for debugging that I removed. (but I can't see it on the commit...)

**Comment by Aneduna** [comment]
The Pokemon Bot Visualizer is awesome, I love seeing the pull requests to see where the project is going

**Comment by nicoschmitt** [comment]
Thanks.
The issue is that other people are starting to work on other similar project and it is becoming kind of a mess to battle for commit in the bot. I'm not even talking about the 2 forks that don't accept the same code...

**Pull request merged**
