### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hilycker**
Link to 'SUPPOSED' new project.

I'd still like to hear something from @NecronomiconCoding first.

### CODE REVIEW

**Comment by SebastienBenazet** [comment]
Is necrobot really dead ?
Why ?

**Comment by Nomaan12345** [comment]
release zip 0.4.0 shows no necrobot exe file

**Comment by xX7** [comment]
What happened? NecronomiconCoding pushed pull requests yesterday and now it's down? Looks fishy from here.?

**Comment by thomasbl** [comment]
gotta hacked and rm'ed? just revert to the latest HEAD and all is ok :)

**Comment by bredmich** [comment]
New project: https://github.com/DurtyFree/PokeMobBot

**Comment by hilycker** [comment]
Closed, seems like @NecronomiconCoding is back.

**Pull request closed without merging**
