### PR TITLE
redone gpx as previous pulls conflicted before it

### PR DESCRIPTION
**Pull request by lilpug**
redone the gpx functions i previously implemented, as conflicted with other pull requests which were done. this adds additional functionality for outputting gpx paths, allowing the user to set number of gpx loops etc

### CODE REVIEW

**Comment by luigidanield2** [comment]
continuo ad avere lo stesso errore di prima .... non capisco perche??? nessun pokestop disponibile trovato nella tua area.distanza massima troppo piccola? prima per un po è partito e dopo un pò mi fa questo.Si può mettere a posto questa cosa? grazie :)
image

**Comment by NecronomiconCoding** [comment]
if you want it in 0.4.0 you gotta fix the conflicts

**Comment by lilpug** [comment]
you don't even use the max walking distance param in the gpx mode when using it so i have no idea why your getting an error to do with none gpx stuff, the only code modified is for the gpx not the walking.

**Comment by lilpug** [comment]
this is going to sound daft, but how do i pull the changed branch again now and then sort out the merge conflicts? first time doing pull request and they don't explain this bit in faq haha.

**Comment by Newgamer1** [comment]
@NecronomiconCoding 

if you want it in 0.4.0 you gotta fix the conflicts

-when do you release 0.4.0?

**Comment by NecronomiconCoding** [comment]
we have some more conflicts.

**Comment by lilpug** [comment]
Daft question how do i see what the conflicts are so i can fix them,  in pretty sure there small bit i just don't know how to see what they are so i can resolve them. First time doing pull requests :)

**Comment by Ilses** [comment]
Try to `git rebase -i origin/master` in a copy of your dev branch

**Comment by lilpug** [comment]
@lles Thanks very much will try in a sec, what do you mean by editors tab :)?

**Comment by lilpug** [comment]
i will be honest i have no idea how to see what the issues are, as i think i should have corrected the 3 conflicts which were just new features added as i was building mine but it still says conflicted still even after the new update push...

**Comment by NecronomiconCoding** [comment]
fix conflicts :smile:

**Pull request closed without merging**
